color: true
recursive: true
reporter: dot
requireMain:
  - "test/support/main.js"
require:
  # - "test/support/babel-register.js"
  - "test/support/coverage.js"
  - "test/support/mode.js"
  - "test/support/args.js"
  - "test/support/log.js"
  - "test/support/chai.js"
  - "test/support/fixtures.js"
slow: 250
