color: true
recursive: true
reporter: dot
require:
  - "test/support/babel.js"
  - "test/support/coverage.js"
  - "test/support/mode.js"
  - "test/support/args.js"
  - "test/support/log.js"
  - "test/support/chai.js"
  - "test/support/fixtures.js"
slow: 250
