language: c

git:
  depth: 9

cache:
  apt: true
  directories:
    - $HOME/.npm
    - $HOME/.node-gyp
    - $NVM
env:
  global:
    - NODE_ENV=test
    - NVM=$HOME/.nvm
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - os: osx
      osx_image: xcode8.3
      compiler: clang

before_install:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      export CC=gcc-7
      export CXX=g++-7
      export DISPLAY=:99.0;
      Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - if [[ ! -d $NVM/.git ]]; then
      rm -rf $NVM;
      git clone https://github.com/creationix/nvm.git $NVM;
    fi
  - git -C $NVM pull -f origin master || true
  - git -C $NVM checkout -f `git -C $NVM describe --abbrev=0 --tags`
  - source $NVM/nvm.sh || true
  - nvm install
  - node --version && npm --version

install:
  - npm install -g node-gyp --no-progress --silent
  - npm install --no-progress --silent

script:
  - node scripts/make lint -- true
  - node scripts/make compile
  - node scripts/make cover

after_success:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
    npm install -g coveralls --no-progress;
      cat ./coverage/lcov.info | coveralls;
    fi

notifications:
  email: false
  slack:
    rooms:
      secure: sj1s7XDF0GINij7mW1GNAWAyHS2rJG1Dx69okM2agu92aAaCKas99d3eWp7N7cLbVO6A68MOvY8zgBIkdp/uebCI6fA2dnVoBPTul8eu9ZanTrXROT9H8vgJ7szyAmnKySCYTfcfJ0k0GyeXlzzoBJwgwwIX3jGYr8G+SoaQYKB7kVzRtkyzVVOXQ+Fuj8xDAVeBfZzxFu8ay5rPuk1/8VyBzHtumZkkCixF6niWGYGIQrJ5zdYwn4XtjiY7tv231JiDKhcHRg7z+CcwYC+rla1EXFoMVNziOq2lgm8s1wWEX87YUV4CwTIgMeRlYOCvgDzx+eGy+UOk8899hsZq9kpqv0y+ai4QoVm1XsdRK6qDvWH7nlPTDZLeSfkY9e+6rn3upRV6XldgnUJSQpEc/bKm3QMNic1E5aCHDAZhh8RhZuyqpEv4GQffhaXvq5jIV6M28ykrC5OZgxVfBH2gj+JPWmaU0/GIHme3P+THasu2Oim8Npi0qmit0UAghiFZHFN47Za5KCu5EctgBQiF3qR5kIaI21BtmEsEfbdlinCm+IvLlv2EJV2/eUvLUowJ9HgFgt3WhBwSa76iZD4js9ZV4H8jzRchRZEI6gwwxhRppeLLm5ZdER97MQqHz7qsWk7LB3javMd4EsTUiUZY8noSXkiMtU7gt89fVgy8OAg=
    on_success: change
    on_failure: change
