branches:
  only:
    - master
skip_tags: true
init:
  - git config --global core.autocrlf true
clone_depth: 8
os: unstable
environment:
  ELECTRON_NO_ATTACH_CONSOLE: true
  nodejs_version: 14
platform:
  - x64
cache:
  #- node_modules -> package.json
  #- '%APPDATA%\npm-cache' -> package.json
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - chcp 65001
  - node --version
  - npm --version
  - npm install sharp sqlite3 --ignore-scripts --no-save --no-package-lock --no-progress --silent
  - npm install --no-optional --no-color --no-progress
  - npm run rebuild -- --force
test_script:
  - npm run -s compile
  - npm run -s test:main -- -C -t 8000 -s 2000
  - npm run -s test:renderer -- -C -t 8000 -s 2000
build: off
