'use strict'

module.exports = {
  activity: require('./activity'),
  classes: require('./classes'),
  context: require('./context'),
  edit: require('./edit'),
  flash: require('./flash'),
  history: require('./history'),
  imports: require('./imports'),
  intl: require('./intl'),
  item: require('./item'),
  keymap: require('./keymap'),
  list: require('./list'),
  metadata: require('./metadata'),
  nav: require('./nav'),
  note: require('./note'),
  ontology: require('./ontology'),
  photo: require('./photo'),
  plugin: require('./plugin'),
  prefs: require('./prefs'),
  project: require('./project'),
  properties: require('./properties'),
  qr: require('./qr'),
  settings: require('./settings'),
  selection: require('./selection'),
  shell: require('./shell'),
  storage: require('./storage'),
  tag: require('./tag'),
  ui: require('./ui'),
  wizard: require('./wizard')
}
