'use strict'

module.exports = {
  ACTIVITY: require('./activity'),
  API: require('./api'),
  CACHE: require('./cache'),
  CONTEXT: require('./context'),
  EDIT: require('./edit'),
  FLASH: require('./flash'),
  ESPER: require('./esper'),
  HISTORY: require('./history'),
  IDLE: require('./idle'),
  IMAGE: require('./image'),
  IMPORTS: require('./import'),
  INTL: require('./intl'),
  ITEM: require('./item'),
  KEYMAP: require('./keymap'),
  LIST: require('./list'),
  LOCALE: require('./locale'),
  METADATA: require('./metadata'),
  MIME: require('./mime'),
  NAV: require('./nav'),
  NOTE: require('./note'),
  NOTEPAD: require('./notepad'),
  ONTOLOGY: require('./ontology'),
  PANEL: require('./panel'),
  PHOTO: require('./photo'),
  PREFS: require('./prefs'),
  PROJECT: require('./project'),
  QR: require('./qr'),
  RECENT: require('./recent'),
  SASS: require('./sass'),
  SELECTION: require('./selection'),
  SETTINGS: require('./settings'),
  SHELL: require('./shell'),
  SIDEBAR: require('./sidebar'),
  STORAGE: require('./storage'),
  TABS: require('./tabs'),
  TAG: require('./tag'),
  TYPE: require('./type'),
  UI: require('./ui'),
  WIZARD: require('./wizard'),
  ...require('./rdf')
}
