export default {
  TPY: 'application/vnd.tropy.tpy',
  MTPY: 'application/vnd.tropy.mtpy',
  TTP: 'application/vnd.tropy.ttp',

  AVIF: 'image/avif',
  EPS: 'image/x-eps',
  GIF: 'image/gif',
  HEIC: 'image/heic',
  HEIF: 'image/heif',
  JPG: 'image/jpeg',
  JPEG: 'image/jpeg',
  JP2: 'image/jp2',
  J2K: 'image/jpeg2000',
  JPX: 'image/jpx',
  JXL: 'image/jxl',
  PDF: 'application/pdf',
  PNG: 'image/png',
  PS: 'application/postscript',
  RAW: 'image/x-dcraw',
  SVG: 'image/svg+xml',
  TIF: 'image/tiff',
  TIFF: 'image/tiff',
  WEBP: 'image/webp'
}
