export default {
  TPY: 'application/vnd.tropy.tpy',
  TTP: 'application/vnd.tropy.ttp',

  AVIF: 'image/avif',
  AVIF_SEQ: 'image/avif-sequence',
  EPS: 'application/eps',
  GIF: 'image/gif',
  HEIC: 'image/heic',
  HEIC_SEQ: 'image/heic-sequence',
  HEIF: 'image/heif',
  HEIF_SEQ: 'image/heif-sequence',
  JPG: 'image/jpeg',
  JPEG: 'image/jpeg',
  JP2: 'image/jp2',
  J2K: 'image/jpeg2000',
  JPX: 'image/jpx',
  PDF: 'application/pdf',
  PNG: 'image/png',
  PS: 'application/postscript',
  SVG: 'image/svg+xml',
  TIF: 'image/tiff',
  TIFF: 'image/tiff',
  WEBP: 'image/webp'
}
