
-- Tropy Terms
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Item', 'fr', "Objet");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Photo', 'fr', "Photo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Selection', 'fr', "Sélection");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Note', 'fr', "Note");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Template', 'fr', "Modèle de saisie");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Field', 'fr', "Champ du modèle de saisie");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#List', 'fr', "Liste");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Tag', 'fr', "Mot-clé");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#date', 'fr', "Date");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#name', 'fr', "Nom");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template', 'fr', "Modèle de saisie");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#photo', 'fr', "Photo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#selection', 'fr', "Sélection de photos");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#box', 'fr', "Carton");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#folder', 'fr', "Dossier");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#piece', 'fr', "Pièce");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#collection', 'fr', "Collection");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template-type', 'fr', "Type");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#domain', 'fr', "Domaine");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#field', 'fr', "Champ");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#property', 'fr', "Propriété");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#datatype', 'fr', "Type de données");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#hint', 'fr', "Indice");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#isRequired', 'fr', "Est obligatoire");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#constant', 'fr', "Constante");

-- DC elements and DC terms
-- http://www.yoyodesign.org/doc/dcmi/dcmi-terms/index.html
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/contributor', 'fr', "Collaborateur");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/coverage', 'fr', "Couverture");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/creator', 'fr', "Créateur");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/date', 'fr', "Date");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/description', 'fr', "Description");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/format', 'fr', "Format");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/identifier', 'fr', "Identificateur");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/language', 'fr', "Langue");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/publisher', 'fr', "Éditeur");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/relation', 'fr', "Relation");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/rights', 'fr', "Droits");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/source', 'fr', "Source");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/subject', 'fr', "Sujet");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/title', 'fr', "Titre");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/type', 'fr', "Type");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/abstract', 'fr', "Résumé");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/accessRights', 'fr', "Droits d'accès");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/accrualMethod', 'fr', "Méthode d'accroissement");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/accrualPeriodicity', 'fr', "Périodicité d'accroissement");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/accrualPolicy', 'fr', "Politique d'accroissement");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/alternative', 'fr', "Titre alternatif");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/audience', 'fr', "Public");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/available', 'fr', "Date de disponibilité");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/bibliographicCitation', 'fr', "Citation bibliographique");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/conformsTo', 'fr', "Conforme à");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/contributor', 'fr', "Collaborateur");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/coverage', 'fr', "Couverture");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/created', 'fr', "Date de création");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/creator', 'fr', "Créateur");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/date', 'fr', "Date");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateAccepted', 'fr', "Date d'acceptation");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateCopyrighted', 'fr', "Date de dépôt des droits d'auteur");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateSubmitted', 'fr', "Date de soumission");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/description', 'fr', "Description");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/educationLevel', 'fr', "Niveau d'éducation du public");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/extent', 'fr', "Étendue");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/format', 'fr', "Format");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasFormat', 'fr', "A pour format");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasPart', 'fr', "A pour partie");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasVersion', 'fr', "A pour version");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/identifier', 'fr', "Identificateur");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/instructionalMethod', 'fr', "Méthode d'enseignement");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isFormatOf', 'fr', "Est un format de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isPartOf', 'fr', "Est une partie de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReferencedBy', 'fr', "Est référencé par");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReplacedBy', 'fr', "Est remplacé par");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isRequiredBy', 'fr', "Est exigé par");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/issued', 'fr', "Date de parution");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isVersionOf', 'fr', "Est une version de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/language', 'fr', "Langue");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/license', 'fr', "Licence");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/mediator', 'fr', "Médiateur");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/medium', 'fr', "Support");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/modified', 'fr', "Date de modification");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/provenance', 'fr', "Provenance");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/publisher', 'fr', "Éditeur");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/references', 'fr', "Référence");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/relation', 'fr', "Relation");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/replaces', 'fr', "Remplace");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/requires', 'fr', "Nécessite");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rights', 'fr', "Droits");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rightsHolder', 'fr', "Détenteur des droits");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/source', 'fr', "Source");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/spatial', 'fr', "Couverture spatiale");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/subject', 'fr', "Sujet");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/tableOfContents', 'fr', "Table des matières");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/temporal', 'fr', "Couverture temporelle");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/title', 'fr', "Titre");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/type', 'fr', "Type");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/valid', 'fr', "Date de validité");
