
-- Tropy Terms
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Item', 'de', "Objekt");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Photo', 'de', "Foto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Selection', 'de', "Ausschnitt");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Note', 'de', "Notiz");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Template', 'de', "Vorlage");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Field', 'de', "Feld");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#List', 'de', "List");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Tag', 'de', "Tag");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#date', 'de', "Datum");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#name', 'de', "Name");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template', 'de', "Template");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#photo', 'de', "Foto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#selection', 'de', "Ausschnitt");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#box', 'de', "Karton");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#folder', 'de', "Ordner");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#piece', 'de', "Stück");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#collection', 'de', "Kollektion");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template-type', 'de', "Vorlagenart");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#domain', 'de', "Domäne");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#field', 'de', "Feld");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#property', 'de', "Eigenschaft");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#datatype', 'de', "Datentyp");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#hint', 'de', "Hinweis");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#isRequired', 'de', "Ist ein Pflichtfeld");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#constant', 'de', "Ist eine Konstante");

-- DC elements and DC terms
-- http://www.yoyodesign.org/doc/dcmi/dcmi-terms/index.html
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/contributor', 'de', "Mitwirkende/r");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/coverage', 'de', "Abdeckung");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/creator', 'de', "Schöpfer/in");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/date', 'de', "Zeitangabe");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/description', 'de', "Beschreibung");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/format', 'de', "Format");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/identifier', 'de', "Identifikator");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/language', 'de', "Sprache");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/publisher', 'de', "Herausgeber");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/relation', 'de', "Beziehung");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/rights', 'de', "Rechteverwaltung");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/source', 'de', "Quelle");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/subject', 'de', "Thema");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/title', 'de', "Titel");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/type', 'de', "Type");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/abstract', 'de', "Zusammenfassung");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/accessRights', 'de', "Zugangsrechte");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/alternative', 'de', "Alternativer Titel");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/audience', 'de', "Publikum");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/available', 'de', "Verfügbarkeitsdatum");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/bibliographicCitation', 'de', "Bibliografische Referenz");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/conformsTo', 'de', "Entspricht");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/contributor', 'de', "Mitwirkende/r");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/coverage', 'de', "Abdeckung");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/created', 'de', "Schöpfungsdatum");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/creator', 'de', "Schöpfer/in");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/date', 'de', "Zeitangabe");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateAccepted', 'de', "Annahmezeitpunkt");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateSubmitted', 'de', "Abgabedatum");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/description', 'de', "Beschreibung");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/educationLevel', 'de', "Bildungsgrad");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/extent', 'de', "Ausdehnung");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/format', 'de', "Format");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasFormat', 'de', "Hat als Format");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasPart', 'de', "Hat als Bestandteil");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasVersion', 'de', "Hat als Version");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/identifier', 'de', "Identifikator");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isFormatOf', 'de', "Ist Format von");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isPartOf', 'de', "Ist Bestandteil von");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReferencedBy', 'de', "Wird referenziert von");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReplacedBy', 'de', "Wird ersetzt durch");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isRequiredBy', 'de', "Wird benötigt von");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/issued', 'de', "Erscheinungsdatum");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isVersionOf', 'de', "Ist Version von");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/language', 'de', "Sprache");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/license', 'de', "Lizenz");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/mediator', 'de', "Mediator");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/medium', 'de', "Medium");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/modified', 'de', "Geändert");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/provenance', 'de', "Provenienz");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/publisher', 'de', "Herausgeber");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/references', 'de', "Referenzen");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/relation', 'de', "Beziehung");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/replaces', 'de', "Ersetzt");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/requires', 'de', "Benötigt");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rights', 'de', "Rechteverwaltung");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rightsHolder', 'de', "Rechteinhaber/in");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/source', 'de', "Quelle");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/spatial', 'de', "Räumliche Abdeckung");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/subject', 'de', "Thema");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/tableOfContents', 'de', "Inhaltsverzeichnis");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/temporal', 'de', "Zeitliche Abdeckung");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/title', 'de', "Titel");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/type', 'de', "Typ");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/valid', 'de', "Gültigkeitsdatum");
