INSERT INTO vocabularies VALUES('http://www.w3.org/2003/12/exif/ns#','exif','2019-03-02 21:01:44',NULL,1,'Exif Vocabulary','Vocabulary to describe an Exif format picture data. All Exif 2.2 tags are defined as RDF properties, as well as several terms to help this schema.',NULL,NULL);

INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitude','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The latitude, expressed as three values giving the degrees, minutes, and seconds, respectively.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#geo','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Geometric data such as latitude, longitude and altitude. Usually saved as rational number.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An attribute relating to GPS information');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#exifdata','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An Exif IFD data entry');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitudeRef','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Indicates whether the longitude is east or west longitude. ASCII ''E'' indicates east longitude, and ''W'' is west longitude.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearingRef','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Indicates the reference used for giving the bearing to the destination point. ''T'' denotes true direction and ''M'' is magnetic direction.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirection','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The direction of the image when it was captured. The range of values is from 0.00 to 359.99.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#samplesPerPixel','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The number of components per pixel. Since this standard applies to RGB and YCbCr images, the value set for this tag is 3. In JPEG compressed data a JPEG marker is used instead of this tag.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#imageDataStruct','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An attribute relating to image data structure');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#lightSource','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Light source such as Daylight, Tungsten, Flash etc.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#pictTaking','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An attribute relating to Picture-Taking Conditions');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#height','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Height of an object');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#length','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Length of an object. Could be a subProperty of other general schema.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#yCbCrSubSampling','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The sampling ratio of chrominance components in relation to the luminance component. In JPEG compressed data a JPEG marker is used instead of this tag.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#imageDataCharacter','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An attribute relating to image data characteristics');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#exifAttribute','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A property that connects an IFD to one of its entries. Super property which integrates all Exif tags.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#isoSpeedRatings','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Indicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gainControl','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The degree of overall image gain adjustment.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#transferFunction','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A transfer function for the image, described in tabular style. Normally this tag is not necessary, since color space is specified in the color space information tag (ColorSpace).');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#mm','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A length with unit of mm');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#versionInfo','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An attribute relating to Version');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#exposureIndex','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The exposure index selected on the camera or input device at the time the image is captured.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#referenceBlackWhite','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The reference black point value and reference white point value. The color space is declared in a color space information tag, with the default being the value that gives the optimal image characteristics Interoperability these conditions.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#sensingMethod','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The image sensor type on the camera or input device, such as One-chip color area sensor etc.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#pimColorBalance','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'ColorBalance info for print image matching');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#pimInfo','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An attribute relating to print image matching');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitudeRef','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Indicates whether the latitude is north or south latitude. The ASCII value ''N'' indicates north latitude, and ''S'' is south latitude.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#yResolution','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The number of pixels per ResolutionUnit in the ImageLength direction. The same value as XResolution is designated.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#resolution','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'a rational number representing a resolution. Could be a subProperty of other general schema.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#yCbCrCoefficients','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The matrix coefficients for transformation from RGB to YCbCr image data.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#stripByteCounts','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The total number of bytes in each strip. With JPEG compressed data this designation is not needed and is omitted.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#recOffset','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An attribute relating to recording offset');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#artist','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Person who created the image');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsDateStamp','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'date and time information relative to UTC (Coordinated Universal Time). The record format is "YYYY:MM:DD" while converted to W3C-DTF to use in RDF');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#date','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'a date information. Usually saved as YYYY:MM:DD (HH:MM:SS) format in Exif data, but represented here as W3C-DTF format');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#pimBrightness','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Brightness info for print image matching');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#shutterSpeedValue','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Shutter speed. The unit is the APEX (Additive System of Photographic Exposure) setting');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#focalPlaneXResolution','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The number of pixels in the image width (X) direction per FocalPlaneResolutionUnit on the camera focal plane.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistance','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The distance to the destination point.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#subjectLocation','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The location of the main subject in the scene. The value of this tag represents the pixel at the center of the main subject relative to the left edge, prior to rotation processing as per the Rotation tag. The first value indicates the X column number and second indicates the Y row number.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#subjectDistanceRange','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The distance to the subject, such as Macro, Close View or Distant View.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#interoperabilityIndex','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Indicates the identification of the Interoperability rule. ''R98'' = conforming to R98 file specification of Recommended Exif Interoperability Rules (ExifR98) or to DCF basic file stipulated by Design Rule for Camera File System. ''THM'' = conforming to DCF thumbnail file stipulated by Design rule for Camera File System.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#interopInfo','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,replace('An attribute relating to Interoperability. Tags stored in\nInteroperability IFD may be defined dependently to each Interoperability rule.','\n',char(10)));
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#imageWidth','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Image width. The number of columns of image data, equal to the number of pixels per row. In JPEG compressed data a JPEG marker is used instead of this tag.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#width','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Width of an object');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#software','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The name and version of the software or firmware of the camera or image input device used to generate the image.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#flash','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The status of flash when the image was shot.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeed','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The speed of GPS receiver movement.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsDOP','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The GPS DOP (data degree of precision). An HDOP value is written during two-dimensional measurement, and PDOP during three-dimensional measurement.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#customRendered','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The use of special processing on image data, such as rendering geared to output. When special processing is performed, the reader is expected to disable or minimize any further processing.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitude','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Latitude of destination, expressed as three values giving the degrees, minutes, and seconds, respectively.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsSatellites','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The GPS satellites used for measurements. This tag can be used to describe the number of satellites, their ID number, angle of elevation, azimuth, SNR and other information in ASCII notation. The format is not specified. If the GPS receiver is incapable of taking measurements, value of the tag shall be set to NULL.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#subSecTimeOriginal','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'DateTimeOriginal subseconds');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#dateAndOrTime','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An attribute relating to Date and/or Time');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#make','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Manufacturer of image input equipment');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#whiteBalance','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The white balance mode set when the image was shot.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#apertureValue','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The lens aperture. The unit is the APEX value.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitude','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The altitude based on the reference in GPSAltitudeRef. Altitude is expressed as one RATIONAL value. The reference unit is meters.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsDifferential','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Indicates whether differential correction is applied to the GPS receiver.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#flashEnergy','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The strobe energy at the time the image is captured, as measured in Beam Candle Power Seconds (BCPS).');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#relatedImageLength','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Related image length');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#cfaPattern','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used. It does not apply to all sensing methods.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#exposureMode','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'the exposure mode set when the image was shot. In auto-bracketing mode, the camera shoots a series of frames of the same scene at different exposure settings.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#fileSource','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The image source. If a DSC recorded the image, this tag value of this tag always be set to 3, indicating that the image was recorded on a DSC.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitudeRef','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Reference for longitude of destination');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#focalLengthIn35mmFilm','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The equivalent focal length assuming a 35mm film camera, in mm. A value of 0 means the focal length is unknown. Note that this tag differs from the FocalLength tag.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#tagid','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The Exif tag number with context prefix, such as IFD type or maker name');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#tag_number','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The Exif tag number');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#saturation','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The direction of saturation processing applied by the camera when the image was shot.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistanceRef','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Indicates the unit used to express the distance to the destination point. ''K'', ''M'' and ''N'' represent kilometers, miles and knots.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#compressedBitsPerPixel','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Information specific to compressed data. The compression mode used for a compressed image is indicated in unit bits per pixel.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#imageConfig','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An attribute relating to Image Configuration');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#focalLength','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The actual focal length of the lens, in mm. Conversion is not made to the focal length of a 35 mm film camera.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#dateTime','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The date and time of image creation. In this standard it is the date and time the file was changed.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo_IFD_Pointer','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A pointer to the GPS IFD, which is a set of tags for recording GPS information.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#ifdPointer','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A tag that refers a child IFD');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#jpegInterchangeFormat','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The offset to the start byte (SOI) of JPEG compressed thumbnail data. This is not used for primary image JPEG data.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#exposureProgram','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The class of the program used by the camera to set exposure when the picture is taken.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#sceneType','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The type of scene. If a DSC recorded the image, this tag value shall always be set to 1, indicating that the image was directly photographed.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#bitsPerSample','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The number of bits per image component. In this standard each component of the image is 8 bits, so the value for this tag is 8. See also SamplesPerPixel. In JPEG compressed data a JPEG marker is used instead of this tag.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#exifVersion','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Exif Version');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#focalPlaneYResolution','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The number of pixels in the image height (Y) direction per FocalPlaneResolutionUnit on the camera focal plane.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#brightnessValue','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The value of brightness. The unit is the APEX value. Ordinarily it is given in the range of -99.99 to 99.99. Note that if the numerator of the recorded value is FFFFFFFF.H, Unknown shall be indicated.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#flashpixVersion','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The Flashpix format version supported by a FPXR file. If the FPXR function supports Flashpix format Ver. 1.0, this is indicated similarly to ExifVersion by recording "0100" as 4-byte ASCII.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsVersionID','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The version of GPSInfoIFD. The version is given as 2.2.0.0. This tag is mandatory when GPSInfo tag is present.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#deviceSettingDescription','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Information on the picture-taking conditions of a particular camera model. The tag is used only to indicate the picture-taking conditions in the reader.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsTrackRef','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The reference for giving the direction of GPS receiver movement. ''T'' denotes true direction and ''M'' is magnetic direction.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeedRef','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The unit used to express the GPS receiver speed of movement. ''K'' ''M'' and ''N'' represents kilometers per hour, miles per hour, and knots.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#meteringMode','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Metering mode, such as CenterWeightedAverage, Spot, MultiSpot,Pattern, Partial etc.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#exposureTime','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Exposure time, given in seconds (sec).');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#seconds','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'a mesurement of time length with unit of second');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearing','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The bearing to the destination point. The range of values is from 0.00 to 359.99.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#compression','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The compression scheme used for the image data. When a primary image is JPEG compressed, this designation is not necessary and is omitted. When thumbnails use JPEG compression, this tag value is set to 6.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#sceneCaptureType','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The type of scene that was shot. It can also be used to record the mode in which the image was shot, such as Landscape, Portrait etc. Note that this differs from the scene type (SceneType) tag.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#pimContrast','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Contrast info for print image matching');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#relatedFile','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Tag Relating to Related File Information');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#_unknown','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An Exif tag whose meaning is not known');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeOriginal','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The date and time when the original image data was generated. For a DSC the date and time the picture was taken are recorded.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitudeRef','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Indicates the altitude used as the reference altitude. If the reference is sea level and the altitude is above sea level, 0 is given. If the altitude is below sea level, a value of 1 is given and the altitude is indicated as an absolute value in the GPSAltitude tag. The reference unit is meters.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#yCbCrPositioning','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The position of chrominance components in relation to the luminance component. This field is designated only for JPEG compressed data or uncompressed YCbCr data.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#oecf','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Indicates the Opto-Electric Conversion Function (OECF) specified in ISO 14524. OECF is the relationship between the camera optical input and the image values.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#model','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Model of image input equipment');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#pimSaturation','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Saturation info for print image matching');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsAreaInformation','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A character string recording the name of the GPS area. The first byte indicates the character code used, and this is followed by the name of the GPS area.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#colorSpace','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The color space information tag (ColorSpace) is always recorded as the color space specifier. Normally sRGB (=1) is used to define the color space based on the PC monitor conditions and environment.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#pixelXDimension','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Information specific to compressed data. When a compressed file is recorded, the valid width of the meaningful image shall be recorded in this tag, whether or not there is padding data or a restart marker. This tag should not exist in an uncompressed file.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#printImageMatching_IFD_Pointer','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A pointer to the print image matching IFD');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#planarConfiguration','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Indicates whether pixel components are recorded in chunky or planar format. In JPEG compressed files a JPEG marker is used instead of this tag. If this field does not exist, the TIFF default of 1 (chunky) is assumed.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsTrack','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The direction of GPS receiver movement. The range of values is from 0.00 to 359.99.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#photometricInterpretation','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Pixel composition. In JPEG compressed data a JPEG marker is used instead of this tag.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#pimSharpness','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Sharpness info for print image matching');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#spectralSensitivity','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Indicates the spectral sensitivity of each channel of the camera used. The tag value is an ASCII string compatible with the standard developed by the ASTM Technical committee.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#focalPlaneResolutionUnit','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The unit for measuring FocalPlaneXResolution and FocalPlaneYResolution. This value is the same as the ResolutionUnit.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#exif_IFD_Pointer','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A pointer to the Exif IFD, which is a set of tags for recording Exif-specific attribute information.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#meter','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A length with unit of meter');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#contrast','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The direction of contrast processing applied by the camera when the image was shot.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#subjectArea','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The location and area of the main subject in the overall scene.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#spatialFrequencyResponse','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'This tag records the camera or input device spatial frequency table and SFR values in the direction of image width, image height, and diagonal direction, as specified in ISO 12233.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#subjectDistance','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The distance to the subject, given in meters. Note that if the numerator of the recorded value is FFFFFFFF.H, Infinity shall be indicated; and if the numerator is 0, Distance unknown shall be indicated.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#imageDescription','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A character string giving the title of the image. It may be a comment such as "1988 company picnic" or the like. Two-byte character codes cannot be used. When a 2-byte code is necessary, the Exif Private tag UserComment is to be used.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsMapDatum','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The geodetic survey data used by the GPS receiver. If the survey data is restricted to Japan, the value of this tag is ''TOKYO'' or ''WGS-84''. If a GPS Info tag is recorded, it is strongly recommended that this tag be recorded.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#subSecTime','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'DateTime subseconds');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirectionRef','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The reference for giving the direction of the image when it is captured. ''T'' denotes true direction and ''M'' is magnetic direction.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitude','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The longitude, expressed as three values giving the degrees, minutes, and seconds, respectively.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#maxApertureValue','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The smallest F number of the lens. The unit is the APEX value. Ordinarily it is given in the range of 00.00 to 99.99, but it is not limited to this range.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeDigitized','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The date and time when the image was stored as digital data. If, for example, an image was captured by DSC and at the same time the file was recorded, then the DateTimeOriginal and DateTimeDigitized will have the same contents.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsStatus','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The status of the GPS receiver when the image is recorded. ''A'' means measurement is in progress, and ''V'' means the measurement is Interoperability.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#digitalZoomRatio','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The digital zoom ratio when the image was shot. If the numerator of the recorded value is 0, this indicates that digital zoom was not used.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#relatedImageWidth','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Related image width');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#datatype','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The Exif field data type, such as ascii, byte, short etc.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsTimeStamp','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The time as UTC (Coordinated Universal Time). TimeStamp is expressed as three RATIONAL values giving the hour, minute, and second.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#stripOffsets','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'For each strip, the byte offset of that strip. With JPEG compressed data this designation is not needed and is omitted.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#xResolution','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The number of pixels per ResolutionUnit in the ImageWidth direction. When the image resolution is unknown, 72 [dpi] is designated.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#imageLength','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Image height. The number of rows of image data. In JPEG compressed data a JPEG marker is used.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#primaryChromaticities','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The chromaticity of the three primary colors of the image. Normally this tag is not necessary, since color space is specified in the color space information tag (ColorSpace).');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#interoperability_IFD_Pointer','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A pointer to the Interoperability IFD, which is composed of tags storing the information to ensure the Interoperability');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitude','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Longitude of destination, expressed as three values giving the degrees, minutes, and seconds, respectively.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#userInfo','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An attribute relating to User Information');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#relatedSoundFile','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Related audio file');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#whitePoint','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The chromaticity of the white point of the image. Normally this tag is not necessary, since color space is specified in the color space information tag (ColorSpace).');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#orientation','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The image orientation viewed in terms of rows and columns.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#subSecTimeDigitized','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'DateTimeDigitized subseconds');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#userComment','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A tag for Exif users to write keywords or comments on the image besides those in ImageDescription, and without the character code limitations of the ImageDescription tag. The character code used in the UserComment tag is identified based on an ID code in a fixed 8-byte area at the start of the tag data area.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitudeRef','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Reference for latitude of destination');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#relatedImageFileFormat','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Related image file format');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#resolutionUnit','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The unit for measuring XResolution and YResolution. The same unit is used for both XResolution and YResolution. If the image resolution in unknown, 2 (inches) is designated.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#makerNote','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Manufacturer notes');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#copyright','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Copyright information. In this standard the tag is used to indicate both the photographer and editor copyrights. It is the copyright notice of the person or organization claiming rights to the image.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#subseconds','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A tag used to record fractions of seconds for a date property');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#rowsPerStrip','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The number of rows per strip. This is the number of rows in the image of one strip when an image is divided into strips. With JPEG compressed data this designation is not needed and is omitted.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#pixelYDimension','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Information specific to compressed data. When a compressed file is recorded, the valid height of the meaningful image shall be recorded in this tag, whether or not there is padding data or a restart marker. This tag should not exist in an uncompressed file. Since data padding is unnecessary in the vertical direction, the number of lines recorded in this valid image height tag will in fact be the same as that recorded in the SOF.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsMeasureMode','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The GPS measurement mode. ''2'' means two-dimensional measurement and ''3'' means three-dimensional measurement is in progress.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#gpsProcessingMethod','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'A character string recording the name of the method used for location finding. The first byte indicates the character code used, and this is followed by the name of the method.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#imageUniqueID','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'An identifier assigned uniquely to each image. It is recorded as an ASCII string equivalent to hexadecimal notation and 128-bit fixed length.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#sharpness','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The direction of sharpness processing applied by the camera when the image was shot.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#jpegInterchangeFormatLength','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The number of bytes of JPEG compressed thumbnail data. This is not used for primary image JPEG data.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#fNumber','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'F number');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#componentsConfiguration','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Information specific to compressed data. The channels of each component are arranged in order from the 1st component to the 4th. For uncompressed data the data arrangement is given in the PhotometricInterpretation tag. However, since PhotometricInterpretation can only express the order of Y,Cb and Cr, this tag is provided for cases when compressed data uses components other than Y, Cb, and Cr and to enable support of other sequences.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#exposureBiasValue','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'The exposure bias. The unit is the APEX value. Ordinarily it is given in the range of -99.99 to 99.99.');
INSERT INTO properties VALUES('http://www.w3.org/2003/12/exif/ns#interoperabilityVersion','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,NULL,NULL,'Interoperability Version');

INSERT INTO classes VALUES('http://www.w3.org/2003/12/exif/ns#IFD','http://www.w3.org/2003/12/exif/ns#',NULL,NULL,'An Image File Directory');

INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#IFD','en','IFD');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#_unknown','en','Unknown tag');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#apertureValue','en','ApertureValue');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#artist','en','Artist');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#bitsPerSample','en','BitsPerSample');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#brightnessValue','en','BrightnessValue');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#cfaPattern','en','CFAPattern');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#colorSpace','en','ColorSpace');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#componentsConfiguration','en','ComponentsConfiguration');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#compressedBitsPerPixel','en','CompressedBitsPerPixel');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#compression','en','Compression');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#contrast','en','Contrast');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#copyright','en','Copyright');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#customRendered','en','CustomRendered');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#datatype','en','Data Type');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#date','en','Date');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateAndOrTime','en','Date and/or Time');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTime','en','DateTime');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeDigitized','en','DateTimeDigitized');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeOriginal','en','DateTimeOriginal');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#deviceSettingDescription','en','DeviceSettingDescription');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#digitalZoomRatio','en','DigitalZoomRatio');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifAttribute','en','Exif Attribute');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifVersion','en','ExifVersion');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exif_IFD_Pointer','en','Exif IFD Pointer');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifdata','en','Exif data');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureBiasValue','en','ExposureBiasValue');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureIndex','en','ExposureIndex');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureMode','en','ExposureMode');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureProgram','en','ExposureProgram');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureTime','en','ExposureTime');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#fNumber','en','FNumber');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#fileSource','en','FileSource');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flash','en','Flash');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flashEnergy','en','FlashEnergy');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flashpixVersion','en','FlashpixVersion');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLength','en','FocalLength');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLengthIn35mmFilm','en','FocalLengthIn35mmFilm');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalPlaneResolutionUnit','en','FocalPlaneResolutionUnit');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalPlaneXResolution','en','FocalPlaneXResolution');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalPlaneYResolution','en','FocalPlaneYResolution');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gainControl','en','GainControl');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#geo','en','Geometric data');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitude','en','Altitude');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitudeRef','en','Altitude Ref.');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAreaInformation','en','Area Information');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDOP','en','DOP');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDateStamp','en','Datestamp');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearing','en','Bearing');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearingRef','en','Bearing Ref.');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistance','en','Distance');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistanceRef','en','Distance Ref.');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitude','en','Dest. Latitude');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitudeRef','en','Dest. Latitude Ref.');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitude','en','Dest. Longitude');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitudeRef','en','Dest. Longitude Ref.');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDifferential','en','Differential Correction');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirection','en','Image Direction');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirectionRef','en','Image Direction Ref.');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo','en','GPS Info');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo_IFD_Pointer','en','GPSInfo IFD Pointer');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitude','en','Latitude');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitudeRef','en','Latitude Ref.');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitude','en','Longitude');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitudeRef','en','Longitude Ref.');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMapDatum','en','Map Datum');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMeasureMode','en','Measure Mode');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsProcessingMethod','en','Processing Method');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSatellites','en','Satellites');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeed','en','Receiver Movement');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeedRef','en','Receiver Movement Ref.');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsStatus','en','Status');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTimeStamp','en','TimeStamp');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTrack','en','Track');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTrackRef','en','Track Ref');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsVersionID','en','Version ID');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#height','en','Height');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#ifdPointer','en','IFD Pointer');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageConfig','en','Image Config');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageDataCharacter','en','Image Data Character');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageDataStruct','en','Image Data Structure');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageDescription','en','ImageDescription');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageLength','en','ImageLength');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageUniqueID','en','ImageUniqueID');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageWidth','en','ImageWidth');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#interopInfo','en','Interoperability Info');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#interoperabilityIndex','en','InteroperabilityIndex');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#interoperabilityVersion','en','InteroperabilityVersion');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#interoperability_IFD_Pointer','en','Interoperability IFD Pointer');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#isoSpeedRatings','en','ISOSpeedRatings');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#jpegInterchangeFormat','en','JPEGInterchangeFormat');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#jpegInterchangeFormatLength','en','JPEGInterchangeFormatLength');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#length','en','Length');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#lightSource','en','LightSource');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#make','en','Make');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#makerNote','en','MakerNote');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#maxApertureValue','en','MaxApertureValue');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#meter','en','Meter');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#meteringMode','en','MeteringMode');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#mm','en','Milimeter');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#model','en','Model');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#oecf','en','OECF');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#orientation','en','Orientation');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#photometricInterpretation','en','PhotometricInterpretation');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pictTaking','en','PictTaking');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimBrightness','en','PrintIM Brightness');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimColorBalance','en','PrintIM ColorBalance');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimContrast','en','PrintIM Contrast');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimInfo','en','PIM Info');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimSaturation','en','PrintIM Saturation');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimSharpness','en','PrintIM Sharpness');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pixelXDimension','en','PixelXDimension');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pixelYDimension','en','PixelYDimension');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#planarConfiguration','en','PlanarConfiguration');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#primaryChromaticities','en','PrimaryChromaticities');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#printImageMatching_IFD_Pointer','en','PrintImageMatching IFD Pointer');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#recOffset','en','Recording Offset');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#referenceBlackWhite','en','ReferenceBlackWhite');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#relatedFile','en','Related File');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#relatedImageFileFormat','en','RelatedImageFileFormat');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#relatedImageLength','en','RelatedImageLength');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#relatedImageWidth','en','RelatedImageWidth');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#relatedSoundFile','en','RelatedSoundFile');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#resolution','en','Resolution');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#resolutionUnit','en','ResolutionUnit');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#rowsPerStrip','en','RowsPerStrip');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#samplesPerPixel','en','SamplesPerPixel');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#saturation','en','Saturation');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#sceneCaptureType','en','SceneCaptureType');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#sceneType','en','SceneType');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#seconds','en','Seconds');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#sensingMethod','en','SensingMethod');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#sharpness','en','Sharpness');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#shutterSpeedValue','en','ShutterSpeedValue');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#software','en','Software');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#spatialFrequencyResponse','en','SpatialFrequencyResponse');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#spectralSensitivity','en','SpectralSensitivity');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#stripByteCounts','en','StripByteCounts');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#stripOffsets','en','StripOffsets');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subSecTime','en','SubSecTime');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subSecTimeDigitized','en','SubSecTimeDigitized');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subSecTimeOriginal','en','SubSecTimeOriginal');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subjectArea','en','SubjectArea');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subjectDistance','en','SubjectDistance');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subjectDistanceRange','en','SubjectDistanceRange');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subjectLocation','en','SubjectLocation');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subseconds','en','Subseconds');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#tag_number','en','Tag number');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#tagid','en','Tag ID');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#transferFunction','en','TransferFunction');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#userComment','en','UserComment');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#userInfo','en','User Info');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#versionInfo','en','Version Info');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#whiteBalance','en','WhiteBalance');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#whitePoint','en','WhitePoint');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#width','en','Width');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#xResolution','en','XResolution');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#yCbCrCoefficients','en','YCbCrCoefficients');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#yCbCrPositioning','en','YCbCrPositioning');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#yCbCrSubSampling','en','YCbCrSubSampling');
INSERT INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#yResolution','en','YResolution');
