------------------------------------------------------------------------------
-- Exif Labels
------------------------------------------------------------------------------

-- English
------------------------------------------------------------------------------
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitude','en','Altitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitudeRef','en','Altitude Ref.');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAreaInformation','en','Area Information');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDOP','en','DOP');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDateStamp','en','Datestamp');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearing','en','Bearing');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearingRef','en','Bearing Ref.');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistance','en','Distance');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistanceRef','en','Distance Ref.');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitude','en','Dest. Latitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitudeRef','en','Dest. Latitude Ref.');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitude','en','Dest. Longitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitudeRef','en','Dest. Longitude Ref.');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDifferential','en','Differential Correction');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirection','en','Image Direction');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirectionRef','en','Image Direction Ref.');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitude','en','Latitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitudeRef','en','Latitude Ref.');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitude','en','Longitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitudeRef','en','Longitude Ref.');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMapDatum','en','Map Datum');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMeasureMode','en','Measure Mode');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsProcessingMethod','en','Processing Method');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSatellites','en','Satellites');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeed','en','Receiver Movement');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeedRef','en', 'Receiver Movement Ref.');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsStatus','en','Status');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTimeStamp','en','TimeStamp');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTrack','en','Track');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTrackRef','en','Track Ref');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsVersionID','en','Version ID');

-- French
------------------------------------------------------------------------------
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitude','fr','Altitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAreaInformation','fr','Informations sur la zone');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDOP','fr','DOP');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearing','fr','Direction');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistance','fr','Distance');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDifferential','fr','Correction différentielle');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirection','fr','Direction de l''image');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMapDatum','fr','Système géodésique');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsProcessingMethod','fr','Méthode de traitement');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeed','fr','Mouvement récepteur');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTimeStamp','fr','Horodatage');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsVersionID','fr','Version de balise');

-- German
------------------------------------------------------------------------------
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#IFD','de','IFD');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#_unknown','de','Unbekannt');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#apertureValue','de','Blendenzahl');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#artist','de','Fotograf/in');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#brightnessValue','de','BrightnessValue');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#colorSpace','de','Farbraum');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#compression','de','Kompression');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#contrast','de','Kontrast');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#copyright','de','Copyright');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#datatype','de','Datentyp');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#date','de','Datum');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateAndOrTime','de','Datum und/oder Uhrzeit');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTime','de','Datum/Uhrzeit');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeDigitized','de','Digitalisierungsdatum');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeOriginal','de','Aufnahmedatum');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifAttribute','de','Exif Attribut');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifVersion','de','Exif Version');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureTime','de','Belichtungszeit');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#fNumber','de','Blendenzahl');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flash','de','Blitz');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flashpixVersion','de','Flashpix Version');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLength','de','Brennweite');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLengthIn35mmFilm','de','Brennweite In 35mm');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#geo','de','Geometrische Daten');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitude','de','Höhe');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitudeRef','de','Referenzhöhe');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAreaInformation','de','Gebietsinformationen');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDOP','de','GPSDOP');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDateStamp','de','Datumstempel');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearing','de','Richtung');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearingRef','de','Richtungsreferenz');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistance','de','Entfernung');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistanceRef','de','Entfernungsreferenz');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitude','de','Ziel-Breite');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitudeRef','de','Ziel-Breitenreferenz');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitude','de','Ziel-Länge');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitudeRef','de','Ziel-Längenreferenz');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDifferential','de','Differentielle Korrektur');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirection','de','Bildrichtung');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirectionRef','de','Bildrichtungsreferenz');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo','de','GPS Info');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo_IFD_Pointer','de','GPSInfo IFD Pointer');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitude','de','Breite');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitudeRef','de','Breitenreferenz');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitude','de','Länge');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitudeRef','de','Längenreferenz');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMapDatum','de','Kartendatum');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMeasureMode','de','Messmethode');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsProcessingMethod','de','Verarbeitungsmethode');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSatellites','de','Satelliten');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeed','de','Empfänger-Bewegung');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeedRef','de','Empfänger-Bewegungsreferenz');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsStatus','de','Status');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTimeStamp','de','Zeitstempel');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsVersionID','de','Tag-Version');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#height','de','Höhe');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageDescription','de','Bildbeschreibung');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageLength','de','Bildlänge');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageWidth','de','Bildbreite');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#isoSpeedRatings','de','ISO');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#length','de','Länge');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#lightSource','de','Lichtquelle');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#make','de','Ausführung');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#makerNote','de','MakerNote');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#meteringMode','de','Messmodus');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#model','de','Modell');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#oecf','de','OECF');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#orientation','de','Ausrichtung');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#resolution','de','Auflösung');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#saturation','de','Sättigung');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#seconds','de','Sekunden');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#software','de','Software');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#tag_number','de','Tag Nummer');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#tagid','de','Tag ID');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#userComment','de','Kommentar');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#userInfo','de','User Info');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#versionInfo','de','Versions Info');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#whiteBalance','de','Weißabgleichk');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#width','de','Breite');

-- Japanese
------------------------------------------------------------------------------
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#IFD','ja','IFD');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#apertureValue','ja','絞り値');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#colorSpace','ja','色空間情報');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#componentsConfiguration','ja','各コンポーネントの意味');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#compressedBitsPerPixel','ja','画像圧縮モード');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#copyright','ja','著作権');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#customRendered','ja','カスタムイメージ処理');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeDigitized','ja','デジタルデータの生成日時');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeOriginal','ja','現画像データの生成日時');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#deviceSettingDescription','ja','DeviceSettingDescription');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#digitalZoomRatio','ja','デジタルズーム比');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifVersion','ja','Exifバージョン');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureBiasValue','ja','露光補正値');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureMode','ja','露出モード');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureProgram','ja','露出プログラム');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureTime','ja','露出時間');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#fNumber','ja','絞り値(F)');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flash','ja','フラッシュ');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flashpixVersion','ja','対応FlashPixバージョン');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLength','ja','レンズ焦点距離');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLengthIn35mmFilm','ja','焦点距離の35mm換算値');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#isoSpeedRatings','ja','ISO感度');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#lightSource','ja','光源');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#makerNote','ja','メーカーノート');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#meteringMode','ja','測光方式');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pixelXDimension','ja','実効画像幅');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pixelYDimension','ja','実効画像高さ');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#sceneCaptureType','ja','シーンキャプチャーモード');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#shutterSpeedValue','ja','シャッタースピード');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#spectralSensitivity','ja','スペクトル感度');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#whiteBalance','ja','ホワイトバランス');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitude','ja','高度');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAreaInformation','ja','エリア情報');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDOP','ja','DOP');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistance','ja','距離');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDifferential','ja','誤差修正');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirection','ja','画像方向');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMapDatum','ja','地図データ');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsProcessingMethod','ja','処理方法');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSatellites','ja','衛星');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeed','ja','受信機の移動');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTimeStamp','ja', 'タイムスタンプ');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsVersionID','ja','タグベーション');
