------------------------------------------------------------------------------
-- IPTC, XMP and Photoshop, PLUS label translations
------------------------------------------------------------------------------

-- German
------------------------------------------------------------------------------
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/CreatorContactInfo','de','Kontaktinformation des Erstellers');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/IntellectualGenre','de','Intellektuelles Genre');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/Scene','de','IPTC-Szenencode');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/SubjectCode','de','IPTC-Subjectcode');
--INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AboutCvTerm','de','');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AddlModelInfo','de','Weitere Fotomodell-Informationen');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ArtworkOrObject','de','Kunstwerk oder Objekt');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigImageGUID','de','Kennung des Digitalbilds');
--INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigitalSourceType','de','');
--INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/EmbdEncRightsExpr','de','');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Event','de','Ereignis');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Genre','de','Genre');
--INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LinkedEncRightsExpr','de','');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationCreated','de','Standort der Aufnahme');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationShown','de','Ort des Motivs');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailHeight','de','Max. verfügbare Höhe');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailWidth','de','Max. verfügbare Breite');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ModelAge','de','Alter Fotomodell(e)');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageCode','de','Kennung der gezeigten Organisation');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageName','de','Name der gezeigten Organisation');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImage','de','Gezeigte Person');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImageWDetails','de','Gezeigte Person mit Details');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ProductInImage','de','Gezeigtes Produkt');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/RegistryId','de','Register-Eintrag');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Ancestor','de','');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AncestorID','de','');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AuthorsPosition','de','Die Berufsbezeichnung des Erstellers');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/CaptionWriter','de','Writer Beschreibung');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Category','de','Kategorie');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/City','de','Ort');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ColorMode','de','Farbmodus');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Country','de','Land');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Credit','de','Namensnennung');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DateCreated','de','Erstellungsdatum');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DocumentAncestors','de','');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Headline','de','Überschrift');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/History','de','Verlauf');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ICCProfile','de','ICC-Profil');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Instructions','de','Anweisungen');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Layer','de','Ebene');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerName','de','Ebenenname');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerText','de','Ebenentext');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Source','de','Quelle');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/State','de','Bundesland/Kanton');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/SupplementalCategories','de','');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TextLayers','de','Textebenen');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TransmissionReference','de','Jobkennung');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Urgency','de','Dringlichkeit');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreateDate','de','Erstellungsdatum');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreatorTool','de','Erstellungstool');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/Identifier','de','Kennung');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/Label','de','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/MetadataDate','de','');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/ModifyDate','de','Änderungsdatum');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/Rating','de','Bewertung');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/DerivedFrom','de','');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/DocumentID','de','Dokumentkennung');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/InstanceID','de','Instanzkennung');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/OriginalDocumentID','de','Originale Dokumentkennung');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/RenditionClass','de','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/RenditionParams','de','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Marked','de','');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Certificate','de','Zertifikat');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Owner','de','Copyright-Eigentümer');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/UsageTerms','de','Nutzungsbedingungen');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/WebStatement','de','');
INSERT INTO labels VALUES('http://ns.adobe.com/xmp/identifier/qual/1.0/Scheme','de','Schema');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/CopyrightOwner','de','Copyright-Eigentümer');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageCreator','de','Ersteller des Bildes');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplier','de','Bildanbieter');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplierImageID','de','Bildkennung des Anbieters');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Licensor','de','Lizenzgeber');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/MinorModelAgeDisclosure','de','Alter bei minderj. Fotomodell');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseID','de','Kennung der Fotomodell-Freigabe');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseStatus','de','Status der Fotomodell-Freigabe');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseID','de','Kennung der Eigentum-Freigabe');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseStatus','de','Status der Eigentum-Freigabe');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Version','de','PLUS Version');


-- French
------------------------------------------------------------------------------
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/CreatorContactInfo','fr','Contact créateur');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/IntellectualGenre','fr','Catégorie intellectuelle');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/Scene','fr','Code de scène IPTC');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/SubjectCode','fr','Code de sujet IPTC');
--INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AboutCvTerm','fr','');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AddlModelInfo','fr','Suppl. d''infos sur les modèles');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ArtworkOrObject','fr','Illustration ou objet');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigImageGUID','fr','Identificateur de l''image numérique');
--INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigitalSourceType','fr','');
--INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/EmbdEncRightsExpr','fr','');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Event','fr','Evénement');
--INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Genre','fr','');
--INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LinkedEncRightsExpr','fr','');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationCreated','fr','Emplacement créé');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationShown','fr','Emplacement affiché');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailHeight','fr','Hauteur disponible max.');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailWidth','fr','Largeur disponible max.');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ModelAge','fr','Age des modèles');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageCode','fr','Code de l''organisation représentée');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageName','fr','Nom de l''organisation représentée');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImage','fr','Personne présentée');
--INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImageWDetails','fr','');
--INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ProductInImage','fr','');
INSERT INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/RegistryId','fr','Entrée de registre');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Ancestor','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AncestorID','fr','');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AuthorsPosition','fr','Fonction du créateur');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/CaptionWriter','fr','Rédacteur de description');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Category','fr','');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/City','fr','Ville');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ColorMode','fr','');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Country','fr','Pays');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Credit','fr','Crédit');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DateCreated','fr','Date de création');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DocumentAncestors','fr','');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Headline','fr','Titre');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/History','fr','Historique');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ICCProfile','fr','Profil ICC');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Instructions','fr','Instructions');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Layer','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerName','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerText','fr','');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Source','fr','Source');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/State','fr','Etat/Province');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/SupplementalCategories','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TextLayers','fr','');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TransmissionReference','fr','Identificateur de tâche');
INSERT INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Urgency','fr','Urgence');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreateDate','fr','Date de création');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreatorTool','fr','Application');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/Identifier','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/Label','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/MetadataDate','fr','');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/ModifyDate','fr','Date de modification');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/Rating','fr','Evaluation');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/DerivedFrom','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/DocumentID','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/InstanceID','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/OriginalDocumentID','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/RenditionClass','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/mm/RenditionParams','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Marked','fr','');
--INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Certificate','fr','');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Owner','fr','Titulaire du droit d''auteur');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/UsageTerms','fr','Droits et conditions d''utilisation');
INSERT INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/WebStatement','fr','URL des infos sur les droits d''auteur');
--INSERT INTO labels VALUES('http://ns.adobe.com/xmp/identifier/qual/1.0/Scheme','fr','');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/CopyrightOwner','fr','Titulaire du droit d''auteur');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageCreator','fr','Créateur d''images');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplier','fr','Fournisseur d''images');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplierImageID','fr','ID de l''image du fournisseur');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Licensor','fr','Concédant de licence');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/MinorModelAgeDisclosure','fr','Divulgation âge modèle mineur');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseID','fr','ID de publication du modèle');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseStatus','fr','Etat de la publication du modèle');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseID','fr','ID de publication de propriété');
INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseStatus','fr','Etat de la publication de propriété');
--INSERT INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Version','fr','');
