------------------------------------------------------------------------------
-- IPTC, XMP and Photoshop, PLUS label translations
------------------------------------------------------------------------------

-- German
------------------------------------------------------------------------------
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/CreatorContactInfo','de','Kontaktinformation des Erstellers');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/IntellectualGenre','de','Intellektuelles Genre');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/Scene','de','IPTC-Szenencode');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/SubjectCode','de','IPTC-Themencode');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AboutCvTerm','de','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AddlModelInfo','de','Weitere Fotomodell-Informationen');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ArtworkOrObject','de','Kunstwerk oder Objekt');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigImageGUID','de','Kennung des Digitalbilds');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigitalSourceType','de','');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/EmbdEncRightsExpr','de','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Event','de','Ereignis');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LinkedEncRightsExpr','de','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationCreated','de','Standort der Aufnahme');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationShown','de','Ort des Motivs');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailHeight','de','Max. verfügbare Höhe');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailWidth','de','Max. verfügbare Breite');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ModelAge','de','Alter Fotomodell(e)');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageCode','de','Kennung der gezeigten Organisation');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageName','de','Name der gezeigten Organisation');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImage','de','Gezeigte Person');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImageWDetails','de','Gezeigte Person im Detail');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ProductInImage','de','Gezeigtes Produkt');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/RegistryId','de','Register-Eintrag');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Ancestor','de','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AncestorID','de','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AuthorsPosition','de','Die Berufsbezeichnung des Erstellers');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/CaptionWriter','de','Writer Beschreibung');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Category','de','Kategorie');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/City','de','Ort');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ColorMode','de','Farbmodus');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Country','de','Land');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Credit','de','Namensnennung');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DateCreated','de','Erstellungsdatum');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DocumentAncestors','de','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Headline','de','Überschrift');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/History','de','Verlauf');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ICCProfile','de','ICC-Profil');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Instructions','de','Anweisungen');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Layer','de','Ebene');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerName','de','Ebenenname');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerText','de','Ebenentext');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Source','de','Quelle');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/State','de','Bundesland/Kanton');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/SupplementalCategories','de','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TextLayers','de','Textebenen');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TransmissionReference','de','Übertragungsreferenz');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Urgency','de','Dringlichkeit');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreateDate','de','Erstellungsdatum');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreatorTool','de','Anwendung');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Identifier','de','Kennung');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Label','de','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/MetadataDate','de','');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/ModifyDate','de','Änderungsdatum');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Rating','de','Bewertung');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Marked','de','Copyright-Status');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Certificate','de','Zertifikat');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Owner','de','Copyright-Eigentümer');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/UsageTerms','de','Nutzungsbedingungen');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/WebStatement','de','Copyright Info URL');
REPLACE INTO labels VALUES('http://ns.adobe.com/xmp/identifier/qual/1.0/Scheme','de','Schema');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/CopyrightOwner','de','Copyright-Eigentümer');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageCreator','de','Ersteller des Bildes');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplier','de','Bildanbieter');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplierImageID','de','Bildkennung des Anbieters');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Licensor','de','Lizenzgeber');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/MinorModelAgeDisclosure','de','Alter bei minderj. Fotomodell');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseID','de','Kennung der Fotomodell-Freigabe');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseStatus','de','Status der Fotomodell-Freigabe');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseID','de','Kennung der Eigentum-Freigabe');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseStatus','de','Status der Eigentum-Freigabe');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Version','de','PLUS Version');


-- French
------------------------------------------------------------------------------
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/CreatorContactInfo','fr','Contact créateur');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/IntellectualGenre','fr','Catégorie intellectuelle');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/Scene','fr','Code de scène IPTC');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/SubjectCode','fr','Code de sujet IPTC');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AboutCvTerm','fr','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AddlModelInfo','fr','Suppl. d''infos sur les modèles');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ArtworkOrObject','fr','Illustration ou objet');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigImageGUID','fr','Identificateur de l''image numérique');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigitalSourceType','fr','');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/EmbdEncRightsExpr','fr','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Event','fr','Evénement');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Genre','fr','');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LinkedEncRightsExpr','fr','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationCreated','fr','Emplacement créé');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationShown','fr','Emplacement affiché');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailHeight','fr','Hauteur disponible max.');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailWidth','fr','Largeur disponible max.');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ModelAge','fr','Age des modèles');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageCode','fr','Code de l''organisation représentée');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageName','fr','Nom de l''organisation représentée');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImage','fr','Personne présentée');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImageWDetails','fr','');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ProductInImage','fr','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/RegistryId','fr','Entrée de registre');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Ancestor','fr','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AncestorID','fr','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AuthorsPosition','fr','Fonction du créateur');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/CaptionWriter','fr','Rédacteur de description');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Category','fr','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/City','fr','Ville');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ColorMode','fr','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Country','fr','Pays');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Credit','fr','Crédit');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DateCreated','fr','Date de création');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DocumentAncestors','fr','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Headline','fr','Titre');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/History','fr','Historique');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ICCProfile','fr','Profil ICC');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Instructions','fr','Instructions');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Layer','fr','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerName','fr','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerText','fr','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Source','fr','Source');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/State','fr','Etat/Province');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/SupplementalCategories','fr','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TextLayers','fr','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TransmissionReference','fr','Identificateur de tâche');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Urgency','fr','Urgence');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreateDate','fr','Date de création');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreatorTool','fr','Application');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Identifier','fr','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Label','fr','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/MetadataDate','fr','');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/ModifyDate','fr','Date de modification');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Rating','fr','Evaluation');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Marked','fr','Etat du copyright');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Certificate','fr','');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Owner','fr','Titulaire du droit d''auteur');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/UsageTerms','fr','Droits et conditions d''utilisation');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/WebStatement','fr','URL des infos sur les droits d''auteur');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xmp/identifier/qual/1.0/Scheme','fr','');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/CopyrightOwner','fr','Titulaire du droit d''auteur');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageCreator','fr','Créateur d''images');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplier','fr','Fournisseur d''images');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplierImageID','fr','ID de l''image du fournisseur');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Licensor','fr','Concédant de licence');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/MinorModelAgeDisclosure','fr','Divulgation âge modèle mineur');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseID','fr','ID de publication du modèle');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseStatus','fr','Etat de la publication du modèle');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseID','fr','ID de publication de propriété');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseStatus','fr','Etat de la publication de propriété');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Version','fr','Version PLUS');


-- Japanese
------------------------------------------------------------------------------
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/CreatorContactInfo','ja','作成者のコンタクト先');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/IntellectualGenre','ja','ジャンル');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/Scene','ja','IPTCシーンコード');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/SubjectCode','ja','IPTC件名コード');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Event','ja','イベント');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Genre','ja','ジャンル');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AuthorsPosition','ja','"作成者の役職');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/CaptionWriter','ja','説明記入者');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Category','ja','カテゴリー');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/City','ja','市区町村名');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Country','ja','国名');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Credit','ja','提供元');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DateCreated','ja','作成日');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Headline','ja','見出し');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/History','ja','ヒストリー');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ICCProfile','ja','ICCプロファイル');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Instructions','ja','説明');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Source','ja','所有者または著作権保有者');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/State','ja','郡道府県名');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TransmissionReference','ja','送信記録');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Urgency','ja','重要度');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreateDate','ja','作成日');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreatorTool','ja','アプリケーション');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/ModifyDate','ja','修正日');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Rating','ja','レート');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Marked','ja','著作権の状態');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Owner','ja','所有者');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/UsageTerms','ja','使用権に関する規約');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/WebStatement','ja','著作権情報URL');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/CopyrightOwner','ja','著作権保持者');

