REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#IFD','ja','IFD');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#apertureValue','ja','絞り値');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#colorSpace','ja','色空間情報');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#componentsConfiguration','ja','各コンポーネントの意味');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#compressedBitsPerPixel','ja','画像圧縮モード');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#copyright','ja','著作権');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#customRendered','ja','カスタムイメージ処理');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeDigitized','ja','デジタルデータの生成日時');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeOriginal','ja','現画像データの生成日時');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#deviceSettingDescription','ja','DeviceSettingDescription');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#digitalZoomRatio','ja','デジタルズーム比');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifVersion','ja','Exifバージョン');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureBiasValue','ja','露光補正値');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureMode','ja','露出モード');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureProgram','ja','露出プログラム');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureTime','ja','露出時間');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#fNumber','ja','絞り値(F)');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flash','ja','フラッシュ');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flashpixVersion','ja','対応FlashPixバージョン');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLength','ja','レンズ焦点距離');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLengthIn35mmFilm','ja','焦点距離の35mm換算値');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#isoSpeedRatings','ja','ISO感度');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#lightSource','ja','光源');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#makerNote','ja','メーカーノート');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#meteringMode','ja','測光方式');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pixelXDimension','ja','実効画像幅');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pixelYDimension','ja','実効画像高さ');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#sceneCaptureType','ja','シーンキャプチャーモード');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#shutterSpeedValue','ja','シャッタースピード');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#spectralSensitivity','ja','スペクトル感度');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#whiteBalance','ja','ホワイトバランス');

REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#artist','ja','Artist');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#bitsPerSample','ja','BitsPerSample');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#brightnessValue','ja','BrightnessValue');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#cfaPattern','ja','CFAPattern');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#compression','ja','Compression');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#contrast','ja','Contrast');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#datatype','ja','Data Type');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#date','ja','Date');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateAndOrTime','ja','Date and/or Time');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTime','ja','DateTime');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifAttribute','ja','Exif Attribute');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exif_IFD_Pointer','ja','Exif IFD Pointer');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifdata','ja','Exif data');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureIndex','ja','ExposureIndex');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#fileSource','ja','FileSource');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flashEnergy','ja','FlashEnergy');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalPlaneResolutionUnit','ja','FocalPlaneResolutionUnit');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalPlaneXResolution','ja','FocalPlaneXResolution');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalPlaneYResolution','ja','FocalPlaneYResolution');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gainControl','ja','GainControl');

REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#geo','ja','Geometric data');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitude','ja','GPSAltitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitudeRef','ja','GPSAltitudeRef');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAreaInformation','ja','GPSAreaInformation');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDOP','ja','GPSDOP');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDateStamp','ja','GPSDateStamp');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearing','ja','GPSDestBearing');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearingRef','ja','GPSDestBearingRef');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistance','ja','GPSDestDistance');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistanceRef','ja','GPSDestDistanceRef');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitude','ja','GPSDestLatitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitudeRef','ja','GPSDestLatitudeRef');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitude','ja','GPSDestLongitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitudeRef','ja','GPSDestLongitudeRef');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDifferential','ja','GPSDifferential');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirection','ja','GPSImgDirection');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirectionRef','ja','GPSImgDirectionRef');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo','ja','GPS Info');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo_IFD_Pointer','ja','GPSInfo IFD Pointer');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitude','ja','GPSLatitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitudeRef','ja','GPSLatitudeRef');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitude','ja','GPSLongitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitudeRef','ja','GPSLongitudeRef');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMapDatum','ja','GPSMapDatum');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMeasureMode','ja','GPSMeasureMode');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsProcessingMethod','ja','GPSProcessingMethod');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSatellites','ja','GPSSatellites');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeed','ja','GPSSpeed');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeedRef','ja','GPSSpeedRef');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsStatus','ja','GPSStatus');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTimeStamp','ja','GPSTimeStamp');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTrack','ja','GPSTrack');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTrackRef','ja','GPSTrackRef');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsVersionID','ja','GPSVersionID');

REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#height','ja','Height');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#ifdPointer','ja','IFD Pointer');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageConfig','ja','Image Config');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageDataCharacter','ja','Image Data Character');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageDataStruct','ja','Image Data Structure');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageDescription','ja','ImageDescription');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageLength','ja','ImageLength');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageUniqueID','ja','ImageUniqueID');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageWidth','ja','ImageWidth');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#interopInfo','ja','Interoperability Info');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#interoperabilityIndex','ja','InteroperabilityIndex');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#interoperabilityVersion','ja','InteroperabilityVersion');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#interoperability_IFD_Pointer','ja','Interoperability IFD Pointer');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#jpegInterchangeFormat','ja','JPEGInterchangeFormat');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#jpegInterchangeFormatLength','ja','JPEGInterchangeFormatLength');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#length','ja','Length');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#make','ja','Make');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#maxApertureValue','ja','MaxApertureValue');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#meter','ja','Meter');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#mm','ja','Milimeter');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#model','ja','Model');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#oecf','ja','OECF');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#orientation','ja','Orientation');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#photometricInterpretation','ja','PhotometricInterpretation');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pictTaking','ja','PictTaking');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimBrightness','ja','PrintIM Brightness');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimColorBalance','ja','PrintIM ColorBalance');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimContrast','ja','PrintIM Contrast');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimInfo','ja','PIM Info');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimSaturation','ja','PrintIM Saturation');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#pimSharpness','ja','PrintIM Sharpness');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#planarConfiguration','ja','PlanarConfiguration');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#primaryChromaticities','ja','PrimaryChromaticities');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#printImageMatching_IFD_Pointer','ja','PrintImageMatching IFD Pointer');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#recOffset','ja','Recording Offset');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#referenceBlackWhite','ja','ReferenceBlackWhite');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#relatedFile','ja','Related File');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#relatedImageFileFormat','ja','RelatedImageFileFormat');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#relatedImageLength','ja','RelatedImageLength');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#relatedImageWidth','ja','RelatedImageWidth');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#relatedSoundFile','ja','RelatedSoundFile');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#resolution','ja','Resolution');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#resolutionUnit','ja','ResolutionUnit');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#rowsPerStrip','ja','RowsPerStrip');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#samplesPerPixel','ja','SamplesPerPixel');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#saturation','ja','Saturation');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#sceneType','ja','SceneType');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#seconds','ja','Seconds');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#sensingMethod','ja','SensingMethod');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#sharpness','ja','Sharpness');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#software','ja','Software');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#spatialFrequencyResponse','ja','SpatialFrequencyResponse');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#stripByteCounts','ja','StripByteCounts');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#stripOffsets','ja','StripOffsets');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subSecTime','ja','SubSecTime');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subSecTimeDigitized','ja','SubSecTimeDigitized');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subSecTimeOriginal','ja','SubSecTimeOriginal');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subjectArea','ja','SubjectArea');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subjectDistance','ja','SubjectDistance');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subjectDistanceRange','ja','SubjectDistanceRange');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subjectLocation','ja','SubjectLocation');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#subseconds','ja','Subseconds');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#tag_number','ja','Tag number');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#tagid','ja','Tag ID');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#transferFunction','ja','TransferFunction');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#userComment','ja','UserComment');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#userInfo','ja','User Info');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#versionInfo','ja','Version Info');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#whitePoint','ja','WhitePoint');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#width','ja','Width');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#xResolution','ja','XResolution');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#yCbCrCoefficients','ja','YCbCrCoefficients');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#yCbCrPositioning','ja','YCbCrPositioning');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#yCbCrSubSampling','ja','YCbCrSubSampling');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#yResolution','ja','YResolution');

