------------------------------------------------------------------------------
-- Exif Labels
------------------------------------------------------------------------------

REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#IFD','it','IFD');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#_unknown','it','Sconosciuto');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#apertureValue','it','Apertura');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#artist','it','Autore');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#brightnessValue','it','Luminosità');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#colorSpace','it','Spazio colore');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#compression','it','Compressione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#contrast','it','Contrasto');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#copyright','it','Diritti d''autore');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#datatype','it','Tipo di dati');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#date','it','Data');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateAndOrTime','it','Data e/o ora');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTime','it','Data/ora');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeDigitized','it','Data della digitalizzazione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeOriginal','it','Data originale');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifAttribute','it','Attributi Exif');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifVersion','it','Versione Exif');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureTime','it','Tempo di esposizione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#fNumber','it','Numero F');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flash','it','Flash');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flashpixVersion','it','Versione Flashpix');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLength','it','Lunghezza focale');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLengthIn35mmFilm','it','Lunghezza focale in 35mm');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#geo','it','Dati geografici');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitude','it','Altezza');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitudeRef','it','Altezza usata da riferimento');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAreaInformation','it','Area GPS');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDOP','it','GPSDOP');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDateStamp','it','Datestamp del GPS');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearing','it','Direzione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearingRef','it','Riferimento direzione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistance','it','Distanza dalla destinazione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistanceRef','it','Riferimento distanza della destinazione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitude','it','Latitudine della destinazione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitudeRef','it','Riferimento latitutine della destinazione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitude','it','Longitudine della destinazione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitudeRef','it','Riferimento longitudine della destinazione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDifferential','it','Correzione differenziale');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirection','it','Direzione dell''immagine');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirectionRef','it','Riferimento direzione dell''immagine');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo','it','Info GPS');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo_IFD_Pointer','it','GPSInfo IFD Pointer');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitude','it','Latitudine');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitudeRef','it','Riferimento latitudine');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitude','it','Longitudine');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitudeRef','it','Riferimento longitudine');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMapDatum','it','Riferimento geodetico del GPS');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMeasureMode','it','Modalità di misurazione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsProcessingMethod','it','Modalità di processazione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSatellites','it','Satelliti');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeed','it','Velocità');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeedRef','it','Riferimento velocità');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsStatus','it','Status');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTimeStamp','it','Timestamp');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsVersionID','it','Versione GPSInfoIFD');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#height','it','Altezza');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageDescription','it','Descrizione dell''immagine');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageLength','it','Lunghezza dell''immagine');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageWidth','it','Larghezza dell''immagine');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#isoSpeedRatings','it','ISO');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#length','it','Lunghezza');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#lightSource','it','Fonte di illuminazione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#make','it','Produttore');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#makerNote','it','Note produttore');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#meteringMode','it','Metodo di misura');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#model','it','Modello');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#oecf','it','OECF');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#orientation','it','Orientamento');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#resolution','it','Risoluzione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#saturation','it','Sautrazione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#seconds','it','Secondi');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#software','it','Software');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#tag_number','it','Numero di tag');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#tagid','it','ID del tag');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#userComment','it','Commenti utente');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#userInfo','it','Informazioni utente');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#versionInfo','it','Informazioni di versione');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#whiteBalance','it','Bilanciamento del bianco');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#width','it','Larghezza');

