-- Tropy Terms
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Item', 'it', "Elemento");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Photo', 'it', "Foto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Selection', 'it', "Selezione");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Note', 'it', "Nota");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Template', 'it', "Modello");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Field', 'it', "Campo del modello");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#List', 'it', "Lista");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Tag', 'it', "Tag");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#date', 'it', "Data");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#name', 'it', "Nome");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template', 'it', "Modello");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#photo', 'it', "Foto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#selection', 'it', "Selezione");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#box', 'it', "Scatolone");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#folder', 'it', "Cartella");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#piece', 'it', "Pezzo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#collection', 'it', "Collezione");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template-type', 'it', "Tipo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#domain', 'it', "Domino");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#field', 'it', "Capo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#property', 'it', "Proprietà");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#datatype', 'it', "Tipo di data");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#hint', 'it', "Suggerimento");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#isRequired', 'it', "È richiesto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#constant', 'it', "Costante");

-- DC elements and DC terms
-- Originally based on http://www.websemantico.org/traduzioni/dc/termini.php
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/contributor', 'it', "Autore di contributo subordinato");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/coverage', 'it', "Copertura");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/creator', 'it', "Creatore");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/date', 'it', "Data");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/description', 'it', "Descrizione");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/format', 'it', "Formato");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/identifier', 'it', "Identificatore della risorsa");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/language', 'it', "Lingua");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/publisher', 'it', "Editore");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/relation', 'it', "Relazione");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/rights', 'it', "Diritti");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/source', 'it', "Fonte");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/subject', 'it', "Soggetto e parole chiave");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/title', 'it', "Titolo");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/type', 'it', "Tipo di risorsa");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/abstract', 'it', "Riassunto");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/accessRights', 'it', "Diritti di accesso");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/alternative', 'it', "Alternativo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/audience', 'it', "Pubblico");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/available', 'it', "Disponibile");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/bibliographicCitation', 'it', "Citazione bibliografica");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/conformsTo', 'it', "Conforme a");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/contributor', 'it', "Autore di contributo subordinato");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/coverage', 'it', "Copertura");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/created', 'it', "Creato");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/creator', 'it', "Creatore");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/date', 'it', "Data");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateAccepted', 'it', "Data di accettazione");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateCopyrighted', 'it', "Data di una dichiarazione di diritto");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateSubmitted', 'it', "Data di immissione della risorsa");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/description', 'it', "Descrizione");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/educationLevel', 'it', "Livello di scolarizzazione del pubblico");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/extent', 'it', "Estensione");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/format', 'it', "Formato");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasFormat', 'it', "Ha formato");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasPart', 'it', "Ha parte");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasVersion', 'it', "Ha versione");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/identifier', 'it', "Identificatore della risorsa");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isFormatOf', 'it', "È formato di");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isPartOf', 'it', "È parte di");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReferencedBy', 'it', "È citata da");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReplacedBy', 'it', "È sostituita da");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isRequiredBy', 'it', "È richiesta da");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/issued', 'it', "Emissione");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isVersionOf', 'it', "È versione di");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/language', 'it', "Lingua");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/license', 'it', "Licenza");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/mediator', 'it', "Mediatore");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/medium', 'it', "Mezzo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/modified', 'it', "Modificato");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/provenance', 'it', "Dichiarazione modifiche");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/publisher', 'it', "Editore");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/references', 'it', "Referimenti");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/relation', 'it', "Relatione");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/replaces', 'it', "Sostituisce");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/requires', 'it', "Richiede");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rights', 'it', "Diritti");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rightsHolder', 'it', "Chi detiene i diritti");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/source', 'it', "Fonte");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/spatial', 'it', "Caratteristiche spaziali");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/subject', 'it', "Soggetto e parole chiave");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/tableOfContents', 'it', "Elenco del contenuto");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/temporal', 'it', "Caratteristiche temporali");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/title', 'it', "Titolo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/type', 'it', "Tipo di risorsa");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/valid', 'it', "Data di validità");

