------------------------------------------------------------------------------
-- IPTC, XMP and Photoshop, PLUS label translations
------------------------------------------------------------------------------

REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/CreatorContactInfo','it','Informazioni di contatto del creatore');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/IntellectualGenre','it','Genere intellettuale');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/Scene','it','Codice di scena IPTC');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/SubjectCode','it','Codice soggetto IPTC');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AboutCvTerm','it','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AddlModelInfo','it','Informazioni aggiuntive sul fotomodello');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ArtworkOrObject','it','Opera d''arte o oggetto');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigImageGUID','it','GUID dell''immagine digitale');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigitalSourceType','it','');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/EmbdEncRightsExpr','it','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Event','it','Evento');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LinkedEncRightsExpr','it','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationCreated','it','Luogo dove è stata scattata la foto');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationShown','it','Luogo che appare nell''immagine');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailHeight','it','Altezza massima disponibile');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailWidth','it','Larghezza massima disponibile');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ModelAge','it','Età del fotomodello');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageCode','it','Codice dell''organizzazione che appare nell''immagine');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageName','it','Nome dell''organizzazione che appare nell''immagine');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImage','it','Persona che appare nell''immagine');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImageWDetails','it','Dettagli riguardo la persona che appare nell''immagine');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ProductInImage','it','Prodotto che appare nell''immagine');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/RegistryId','it','ID di registrazione');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Ancestor','it','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AncestorID','it','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AuthorsPosition','it','Professione dell''autore');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/CaptionWriter','it','Autore della didascalia');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Category','it','Categoria');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/City','it','Luogo');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ColorMode','it','Modalità colore');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Country','it','Paese');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Credit','it','Crediti');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DateCreated','it','Data di creazione');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DocumentAncestors','it','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Headline','it','Titolo');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/History','it','Storia');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ICCProfile','it','Profilo ICC');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Instructions','it','Istruzioni');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Layer','it','Strati');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerName','it','Nome di strato');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerText','it','Testo dello strato');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Source','it','Fonte');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/State','it','Regione');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/SupplementalCategories','it','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TextLayers','it','Strati di testo');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TransmissionReference','it','Riferimento alla trasmissione originale');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Urgency','it','Urgenza');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreateDate','it','Data di creazione');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreatorTool','it','Strumento di creazione');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Identifier','it','Identificativo');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Label','it','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/MetadataDate','it','');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/ModifyDate','it','Data di modifica');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Rating','it','Voto');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Marked','it','Diritto d''autore');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Certificate','it','Certificato');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Owner','it','Proprietario');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/UsageTerms','it','Modalità d''uso');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/WebStatement','it','URL diritto d''autore');
REPLACE INTO labels VALUES('http://ns.adobe.com/xmp/identifier/qual/1.0/Scheme','it','Schema');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/CopyrightOwner','it','Proprietario dei diritti d''autore');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageCreator','it','Creatore dell''immagine');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplier','it','Fornitore dell''immagine');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplierImageID','it','Identificativo immagine del fornitore');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Licensor','it','Licenziante');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/MinorModelAgeDisclosure','it','Dichiarazione fotomodello minore');
--REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseID','it','');
--REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseStatus','it','');
--REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseID','it','');
--REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseStatus','it','');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Version','it','Versione PLUS');

