-- Tropy Terms ES
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Item', 'es', "Objeto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Photo', 'es', "Foto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Selection', 'es', "Selección");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Note', 'es', "Nota");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Template', 'es', "Plantilla");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Field', 'es', "Campo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#List', 'es', "Lista");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Tag', 'es', "Etiqueta");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#date', 'es', "Fecha");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#name', 'es', "Nombre");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template', 'es', "Plantilla");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#photo', 'es', "Foto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#selection', 'es', "Selección");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#box', 'es', "Caja");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#folder', 'es', "Fólder");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#piece', 'es', "Pieza");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#collection', 'es', "Colección");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template-type', 'es', "Tipo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#domain', 'es', "Dominio");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#field', 'es', "Campo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#property', 'es', "Propriedad");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#datatype', 'es', "Tipo de dato");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#hint', 'es', "Consejo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#isRequired', 'es', "Obligatorio");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#constant', 'es', "Constante");

-- DC elements and DC terms ES
-- Originally based on http://www.websemantico.org/traduzioni/dc/termini.php
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/contributor', 'es', "Colaborador");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/coverage', 'es', "Covertura");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/creator', 'es', "Creador");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/date', 'es', "Fecha");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/description', 'es', "Descripción");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/format', 'es', "Formato");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/identifier', 'es', "Identificador");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/language', 'es', "Lengua");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/publisher', 'es', "Editor");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/relation', 'es', "Relación");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/rights', 'es', "Derechos");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/source', 'es', "Fuente");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/subject', 'es', "Asunto");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/title', 'es', "Título");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/type', 'es', "Tipo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/abstract', 'es', "Resumen");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/accessRights', 'es', "Derechos de acceso");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/alternative', 'es', "Título alternativo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/audience', 'es', "Audiencia");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/available', 'es', "Fecha de disponibilided");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/bibliographicCitation', 'es', "Cita bibliográfica");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/conformsTo', 'es', "Conforme a");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/contributor', 'es', "Colaborador");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/coverage', 'es', "Covertura");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/created', 'es', "Fecha de creación");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/creator', 'es', "Creador");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/date', 'es', "Fecha");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateAccepted', 'es', "Fecha de acceptación");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateCopyrighted', 'es', "Fecha de depósito de derechos de autor");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateSubmitted', 'es', "Fecha de envío");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/description', 'es', "Descripción");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/educationLevel', 'es', "Nivel de educación");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/extent', 'es', "Alcance");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/format', 'es', "Formato");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasFormat', 'es', "Tiene por formato");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasPart', 'es', "Tiene por parte");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasVersion', 'es', "Tiene por versión");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/identifier', 'es', "Identificador");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isFormatOf', 'es', "Es formato de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isPartOf', 'es', "Es parte de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReferencedBy', 'es', "Es referenciado por");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReplacedBy', 'es', "Es remplazado por");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isRequiredBy', 'es', "Es requerido por");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/issued', 'es', "Emitido");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isVersionOf', 'es', "Es una versión de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/language', 'es', "Lengua");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/license', 'es', "Licencia");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/mediator', 'es', "Mediador");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/medium', 'es', "Medio");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/modified', 'es', "Modificación");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/provenance', 'es', "Provenencia");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/publisher', 'es', "Editor");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/references', 'es', "Referencia");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/relation', 'es', "Relación");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/replaces', 'es', "Remplaza");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/requires', 'es', "Requiere");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rights', 'es', "Derechos");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rightsHolder', 'es', "Detentor de derechos");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/source', 'es', "Fuente");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/spatial', 'es', "Características espaciales");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/subject', 'es', "Asunto");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/tableOfContents', 'es', "Table de contenido");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/temporal', 'es', "Características temporales");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/title', 'es', "Título");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/type', 'es', "Tipo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/valid', 'es', "Fecha de validez");


-- Corrections ES
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/CreatorContactInfo','es','Información de contacto');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/IntellectualGenre','es','Categoría intelectual');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ArtworkOrObject','es','Ilustración u objeto');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigImageGUID','es','Identificador de imagen digital');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationCreated','es','Lugar creado');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationShown','es','Lugar mostrada');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ModelAge','es','Edad de modelos');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/RegistryId','es','Identificador de registro');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplier','es','Proveedor de imagen');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplierImageID','es','Identificador del proveedor de imagen');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Licensor','es','Licenciante');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/MinorModelAgeDisclosure','es','Divulgación de edad de modelo menor');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseID','es','ID de publicación del modelo');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseStatus','es','Estado de publicación del modelo');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseID','es','ID de publicación de la propiedad');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseStatus','es','de publicación del modelo de la propiedad');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Version','es','Version PLUS');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitude','es','Longitud');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#userInfo','es','Información de usuario');
