-- Spanish
------------------------------------------------------------------------------
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/CreatorContactInfo','es','Contact créateur');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/IntellectualGenre','es','Categoría intellectual');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/Scene','es','Código de escena IPTC');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/SubjectCode','es','Código de sujeto IPTC');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AboutCvTerm','es','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/AddlModelInfo','es','Información adicional sobre modelos');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ArtworkOrObject','es','Illustration ou objet');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigImageGUID','es','Identificateur de l''image numérique');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/DigitalSourceType','es','Tipo de la fuente digital');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/EmbdEncRightsExpr','es','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Event','es','Evento');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/Genre','es','Género');
--REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LinkedEncRightsExpr','es','');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationCreated','es','Emplacement créé');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/LocationShown','es','Emplacement affiché');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailHeight','es','Altura máxima disponible.');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/MaxAvailWidth','es','Anchura máxima disponible.');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ModelAge','es','Edad des modelos');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageCode','es','Código de la organización representada');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/OrganisationInImageName','es','Nombre de la organización representada');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImage','es','Persona presentada');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/PersonInImageWDetails','es','Detalles de la persona presentada');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/ProductInImage','es','Producto en imagen');
REPLACE INTO labels VALUES('http://iptc.org/std/Iptc4xmpExt/2008-02-29/RegistryId','es','Entrée de registre');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Ancestor','es','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AncestorID','es','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/AuthorsPosition','es','Función del autor');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/CaptionWriter','es','Redactor de la description');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Category','es','Categoría');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/City','es','Ciudad');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ColorMode','es','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Country','es','País');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Credit','es','Crédito');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DateCreated','es','Fecha de creación');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/DocumentAncestors','es','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Headline','es','Título');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/History','es','Histórico');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/ICCProfile','es','Perfil ICC');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Instructions','es','Instrucciones');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Layer','es','Capa');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerName','es','Nombre de capa');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/LayerText','es','Texto en la capa');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Source','es','Fuente');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/State','es','Estado/Provincia');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/SupplementalCategories','es','Categorías suplementarias');
--REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TextLayers','es','');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/TransmissionReference','es','Identificador de tarea');
REPLACE INTO labels VALUES('http://ns.adobe.com/photoshop/1.0/Urgency','es','Urgencia');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreateDate','es','Fecha de creación');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/CreatorTool','es','Applicación');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Identifier','es','Identificador');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Label','es','');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/MetadataDate','es','');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/ModifyDate','es','Fecha de modificación');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/Rating','es','Evaluación');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Marked','es','Estado del copyright');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Certificate','es','Certificado');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/Owner','es','Titular del derecho de autor');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/UsageTerms','es','Derechos y condiciones de uso');
REPLACE INTO labels VALUES('http://ns.adobe.com/xap/1.0/rights/WebStatement','es','URL de información sobre los derechos de autor');
--REPLACE INTO labels VALUES('http://ns.adobe.com/xmp/identifier/qual/1.0/Scheme','es','');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/CopyrightOwner','es','Titular del derecho de autor');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageCreator','es','Creador de la imagen');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplier','es','Fournisseur d''images');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ImageSupplierImageID','es','ID de l''image du fournisseur');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Licensor','es','Concédant de licence');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/MinorModelAgeDisclosure','es','Divulgation âge modèle mineur');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseID','es','ID de publication du modèle');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/ModelReleaseStatus','es','Etat de la publication du modèle');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseID','es','ID de publication de propriété');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/PropertyReleaseStatus','es','Etat de la publication de propriété');
REPLACE INTO labels VALUES('http://ns.useplus.org/ldf/xmp/1.0/Version','es','Version PLUS');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#IFD','es','IFD');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#_unknown','es','Desconocido');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#apertureValue','es','Apertura');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#artist','es','Artista');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#brightnessValue','es','Luminosidad');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#colorSpace','es','Espacio de color');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#compression','es','Compresión');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#contrast','es','Contraste');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#copyright','es','Derecho de autor');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#datatype','es','Tipo de dato');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#date','es','Fecha');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateAndOrTime','es','Fecha y/u hora');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTime','es','Fecha y hora');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeDigitized','es','Fecha de versión digital');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#dateTimeOriginal','es','Fecha de versión original');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifAttribute','es','Atributo Exif');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exifVersion','es','Versión Exif');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#exposureTime','es','Tiempo de exposición');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#fNumber','es','Número F');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flash','es','Flash');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#flashpixVersion','es','Versión Flashpix');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLength','es','Distancia focal');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#focalLengthIn35mmFilm','es','Distancia focal in 35mm');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#geo','es','Datos geográficos');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitude','es','Altitud');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAltitudeRef','es','Altitud de referencia');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsAreaInformation','es','Información del área');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDOP','es','GPSDOP');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDateStamp','es','Marca de hora del GPS');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearing','es','Dirección');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestBearingRef','es','Referencia de dirección');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistance','es','Distancia del destino');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestDistanceRef','es','Referencia de distancia del destino');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitude','es','Latitud del destino');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLatitudeRef','es','Referencia de latitud del destino');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitude','es','Longitud del destino');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDestLongitudeRef','es','Longitud de referencia del destino');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsDifferential','es','Corrección diferencial');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirection','es','Dirección de la imagen');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsImgDirectionRef','es','Referencia de dirección de la imagen');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo','es','Info GPS');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsInfo_IFD_Pointer','es','GPSInfo IFD Pointer');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitude','es','Latitud');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLatitudeRef','es','Referencia de latitud');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitude','es','Longitude');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsLongitudeRef','es','Referenca de longitud');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMapDatum','es','Sistema geodésico');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsMeasureMode','es','Modo de medida');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsProcessingMethod','es','Método de procesamiento');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSatellites','es','Satélites');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeed','es','Velocidad');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsSpeedRef','es','Velocidad de referencia');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsStatus','es','Status');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsTimeStamp','es','Marca de hora');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#gpsVersionID','es','Versión GPS');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#height','es','Altura');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageDescription','es','Descripción de la imagen');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageLength','es','Largura de imagen');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#imageWidth','es','Anchura de imager');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#isoSpeedRatings','es','ISO');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#length','es','Largura');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#lightSource','es','Fuente de luz');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#make','es','Productor');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#makerNote','es','Nota de la producción');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#meteringMode','es','Modo de medida');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#model','es','Model');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#oecf','es','OECF');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#orientation','es','Orientación');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#resolution','es','Resolución');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#saturation','es','Saturación');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#seconds','es','Segundos');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#software','es','Software');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#tag_number','es','Numero de etiqueta');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#tagid','es','Identificador de la etiqueta');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#userComment','es','Commentarios de usuario');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#userInfo','es','Informatción de usuario');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#versionInfo','es','Información de versión');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#whiteBalance','es','Balance de blancos');
REPLACE INTO labels VALUES('http://www.w3.org/2003/12/exif/ns#width','es','Anchura');
