-- Tropy Terms PT
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Item', 'pt', "Item");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Photo', 'pt', "Foto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Selection', 'pt', "Seleção");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Note', 'pt', "Nota");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Template', 'pt', "Modelo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Field', 'pt', "Campo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#List', 'pt', "Lista");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Tag', 'pt', "Etiqueta");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#date', 'pt', "Data");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#name', 'pt', "Nome");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template', 'pt', "Modelo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#photo', 'pt', "Foto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#selection', 'pt', "Seleção");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#box', 'pt', "Caixa");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#folder', 'pt', "Pasta");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#piece', 'pt', "Peça");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#collection', 'pt', "Coleção");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template-type', 'pt', "Tipo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#domain', 'pt', "Domínio");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#field', 'pt', "Campo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#property', 'pt', "Propriedade");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#datatype', 'pt', "Tipo de dado");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#hint', 'pt', "Dica");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#isRequired', 'pt', "Obrigatório");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#constant', 'pt', "Constante");

-- DC elements and DC terms PT
-- Portuguese version of https://www.dublincore.org/specifications/dublin-core/dces/1999-07-02/
-- Available at http://purl.pt/201/1/

REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/contributor', 'pt', "Outro Contribuinte");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/coverage', 'pt', "Cobertura");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/creator', 'pt', "Criador");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/date', 'pt', "Data");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/description', 'pt', "Descrição");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/format', 'pt', "Formato");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/identifier', 'pt', "Identificador do Recurso");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/language', 'pt', "Língua");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/publisher', 'pt', "Editor");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/relation', 'pt', "Relação");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/rights', 'pt', "Gestão de Direitos");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/source', 'pt', "Fonte");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/subject', 'pt', "Assunto e Palavras Chave");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/title', 'pt', "Título");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/type', 'pt', "Tipo do Recurso");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/abstract', 'pt', "Resumo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/accessRights', 'pt', "Direitos de acesso");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/alternative', 'pt', "Título alternativo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/audience', 'pt', "Audiência");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/available', 'pt', "Data de disponibilização");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/bibliographicCitation', 'pt', "Citação bibliográfica");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/conformsTo', 'pt', "Conforme a");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/contributor', 'pt', "Contribuinte");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/coverage', 'pt', "Cobertura");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/created', 'pt', "Data de criação");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/creator', 'pt', "Criador");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/date', 'pt', "Data");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateAccepted', 'pt', "Data de aceitação");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateCopyrighted', 'pt', "Data de depósito de Direitos de Autor");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateSubmitted', 'pt', "Data de submissão");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/description', 'pt', "Descrição");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/educationLevel', 'pt', "Nível de educação");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/extent', 'pt', "Extensão");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/format', 'pt', "Formato");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasFormat', 'pt', "Tem como formato");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasPart', 'pt', "Tem como parte");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasVersion', 'pt', "Tem como versão");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/identifier', 'pt', "Identificador");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isFormatOf', 'pt', "É formato de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isPartOf', 'pt', "É parte de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReferencedBy', 'pt', "É referenciado por");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReplacedBy', 'pt', "É substituído por");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isRequiredBy', 'pt', "É requerido por");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/issued', 'pt', "Emitido");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isVersionOf', 'pt', "É uma versão de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/language', 'pt', "Língua");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/license', 'pt', "Licença");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/mediator', 'pt', "Mediador");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/medium', 'pt', "Meio");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/modified', 'pt', "Modificação");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/provenance', 'pt', "Proveniência");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/publisher', 'pt', "Editor");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/references', 'pt', "Referencia");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/relation', 'pt', "Relação");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/replaces', 'pt', "Substitui");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/requires', 'pt', "Requer");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rights', 'pt', "Gestão de Direitos");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rightsHolder', 'pt', "Detentor de Direitos");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/source', 'pt', "Fonte");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/spatial', 'pt', "Características espaciais");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/subject', 'pt', "Assunto");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/tableOfContents', 'pt', "Índice");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/temporal', 'pt', "Características temporais");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/title', 'pt', "Título");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/type', 'pt', "Tipo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/valid', 'pt', "Data de validade");

