-- Tropy Terms PT
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Item', 'pt-BR', "Item");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Photo', 'pt-BR', "Foto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Selection', 'pt-BR', "Seleção");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Note', 'pt-BR', "Nota");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Template', 'pt-BR', "Modelo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Field', 'pt-BR', "Campo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#List', 'pt-BR', "Lista");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#Tag', 'pt-BR', "Etiqueta");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#date', 'pt-BR', "Data");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#name', 'pt-BR', "Nome");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template', 'pt-BR', "Modelo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#photo', 'pt-BR', "Foto");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#selection', 'pt-BR', "Seleção");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#box', 'pt-BR', "Caixa");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#folder', 'pt-BR', "Pasta");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#piece', 'pt-BR', "Peça");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#collection', 'pt-BR', "Coleção");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#template-type', 'pt-BR', "Tipo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#domain', 'pt-BR', "Domínio");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#field', 'pt-BR', "Campo");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#property', 'pt-BR', "Propriedade");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#datatype', 'pt-BR', "Tipo de dado");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#hint', 'pt-BR', "Dica");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#isRequired', 'pt-BR', "Obrigatório");
REPLACE INTO labels VALUES ('https://tropy.org/v1/tropy#constant', 'pt-BR', "Constante");

-- DC elements and DC terms pt-BR
-- Portuguese version of https://www.dublincore.org/specifications/dublin-core/dces/1999-07-02/
-- Available at http://purl.pt/201/1/

REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/contributor', 'pt-BR', "Outro Contribuinte");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/coverage', 'pt-BR', "Abrangência");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/creator', 'pt-BR', "Criador");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/date', 'pt-BR', "Data");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/description', 'pt-BR', "Descrição");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/format', 'pt-BR', "Formato");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/identifier', 'pt-BR', "Identificador do Recurso");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/language', 'pt-BR', "Língua");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/publisher', 'pt-BR', "Editor");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/relation', 'pt-BR', "Relação");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/rights', 'pt-BR', "Gestão de Direitos");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/source', 'pt-BR', "Fonte");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/subject', 'pt-BR', "Assunto e Palavras-chave");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/title', 'pt-BR', "Título");
REPLACE INTO labels VALUES ('http://purl.org/dc/elements/1.1/type', 'pt-BR', "Tipo do Recurso");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/abstract', 'pt-BR', "Resumo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/accessRights', 'pt-BR', "Direitos de acesso");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/alternative', 'pt-BR', "Título alternativo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/audience', 'pt-BR', "Audiência");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/available', 'pt-BR', "Data de disponibilização");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/bibliographicCitation', 'pt-BR', "Citação bibliográfica");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/conformsTo', 'pt-BR', "Conformodade com");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/contributor', 'pt-BR', "Contribuinte");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/coverage', 'pt-BR', "Abrangência");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/created', 'pt-BR', "Data de criação");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/creator', 'pt-BR', "Criador");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/date', 'pt-BR', "Data");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateAccepted', 'pt-BR', "Data de aceitação");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateCopyrighted', 'pt-BR', "Data de depósito de Direitos de Autor");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/dateSubmitted', 'pt-BR', "Data de submissão");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/description', 'pt-BR', "Descrição");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/educationLevel', 'pt-BR', "Nível de educação");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/extent', 'pt-BR', "Extensão");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/format', 'pt-BR', "Formato");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasFormat', 'pt-BR', "Tem formato de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasPart', 'pt-BR', "Tem parte de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/hasVersion', 'pt-BR', "Tem como versão");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/identifier', 'pt-BR', "Identificador");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isFormatOf', 'pt-BR', "É formato de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isPartOf', 'pt-BR', "É parte de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReferencedBy', 'pt-BR', "É referenciado por");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isReplacedBy', 'pt-BR', "É substituído por");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isRequiredBy', 'pt-BR', "É requerido por");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/issued', 'pt-BR', "Emitido");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/isVersionOf', 'pt-BR', "É uma versão de");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/language', 'pt-BR', "Língua");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/license', 'pt-BR', "Licença");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/mediator', 'pt-BR', "Mediador");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/medium', 'pt-BR', "Meio");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/modified', 'pt-BR', "Modificação");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/provenance', 'pt-BR', "Proveniência");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/publisher', 'pt-BR', "Editor");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/references', 'pt-BR', "Referencia");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/relation', 'pt-BR', "Relação");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/replaces', 'pt-BR', "Substitui");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/requires', 'pt-BR', "Requer");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rights', 'pt-BR', "Gestão de Direitos");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/rightsHolder', 'pt-BR', "Detentor de Direitos");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/source', 'pt-BR', "Fonte");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/spatial', 'pt-BR', "Abrangência Espacial");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/subject', 'pt-BR', "Assunto");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/tableOfContents', 'pt-BR', "Índice");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/temporal', 'pt-BR', "Abrangência temporal");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/title', 'pt-BR', "Título");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/type', 'pt-BR', "Tipo");
REPLACE INTO labels VALUES ('http://purl.org/dc/terms/valid', 'pt-BR', "Data de validade");
