REPLACE INTO vocabularies VALUES('http://xmlns.com/foaf/0.1/','foaf','2023-04-17T15:12:30.315Z',NULL,1,'Friend of a Friend (FOAF) Vocabulary','The Friend of a Friend (FOAF) RDF vocabulary, described using W3C RDF Schema and the Web Ontology Language.',NULL,NULL);

REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/membershipClass','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'Indicates the class of individuals that are a member of a Group');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/isPrimaryTopicOf','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A document that this thing is the primary topic of.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/mbox','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A  personal mailbox, ie. an Internet mailbox associated with exactly one owner, the first owner of this mailbox. This is a ''static inverse functional property'', in that  there is (across time and change) at most one individual that ever has any particular value for foaf:mbox.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/based_near','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A location that something is based near, for some broadly human notion of near.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/phone','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A phone,  specified using fully qualified tel: URI scheme (refs: http://www.w3.org/Addressing/schemes.html#tel).');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/homepage','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A homepage for some thing.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/page','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A page or document about this thing.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/weblog','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A weblog of some thing (whether person, group, company etc.).');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/openid','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'An OpenID for an Agent.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/tipjar','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A tipjar document for this agent, describing means for payment and reward.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/made','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'Something that was made by this agent.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/maker','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'An agent that  made this thing.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/img','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'An image that can be used to represent some thing (ie. those depictions which are particularly representative of something, eg. one''s photo on a homepage).');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/depiction','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A depiction of some thing.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/depicts','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A thing depicted in this representation.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/thumbnail','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A derived thumbnail image.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/workplaceHomepage','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A workplace homepage of some person; the homepage of an organization they work for.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/workInfoHomepage','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A work info homepage of some person; a page about their work for some organization.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/schoolHomepage','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A homepage of a school attended by the person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/knows','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A person known by this person (indicating some level of reciprocated interaction between the parties).');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/interest','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A page about a topic of interest to this person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/topic_interest','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A thing of interest to this person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/publications','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A link to the publications of this person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/currentProject','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A current project this person works on.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/pastProject','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A project this person has previously worked on.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/fundedBy','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'An organization funding a project or person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/logo','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A logo representing some thing.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/topic','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A topic of some page or document.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/focus','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The underlying or ''focal'' entity associated with some SKOS-described concept.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/theme','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A theme.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/account','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'Indicates an account held by this agent.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/holdsAccount','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'Indicates an account held by this agent.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/accountServiceHomepage','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'Indicates a homepage of the service provide for this online account.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/member','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'Indicates a member of a Group');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/mbox_sha1sum','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The sha1sum of the URI of an Internet mailbox associated with exactly one owner, the  first owner of the mailbox.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/geekcode','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A textual geekcode for this person, see http://www.geekcode.com/geek.html');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/dnaChecksum','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A checksum for the DNA of some thing. Joke.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/sha1','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A sha1sum hash, in hex.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/title','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'Title (Mr, Mrs, Ms, Dr. etc)');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/nick','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A short informal nickname characterising an agent (includes login identifiers, IRC and other chat nicknames).');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/jabberID','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A jabber ID for something.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/aimChatID','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'An AIM chat ID');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/skypeID','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A Skype ID');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/icqChatID','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'An ICQ chat ID');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/yahooChatID','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A Yahoo chat ID');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/msnChatID','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'An MSN chat ID');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/name','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A name for some thing.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/firstName','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The first name of a person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/lastName','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The last name of a person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/givenName','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The given name of some person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/givenname','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The given name of some person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/surname','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The surname of some person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/family_name','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The family name of some person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/familyName','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The family name of some person.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/plan','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A .plan comment, in the tradition of finger and ''.plan'' files.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/myersBriggs','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A Myers Briggs (MBTI) personality classification.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/accountName','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'Indicates the name (identifier) associated with this online account.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/status','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'A string expressing what the user is happy for the general public (normally) to know about their current activity.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/gender','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The gender of this Agent (typically but not necessarily ''male'' or ''female'').');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/primaryTopic','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The primary topic of some page or document.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/birthday','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The birthday of this Agent, represented in mm-dd string form, eg. ''12-31''.');
REPLACE INTO properties VALUES('http://xmlns.com/foaf/0.1/age','http://xmlns.com/foaf/0.1/',NULL,NULL,NULL,NULL,'The age in years of some agent.');

REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/LabelProperty','http://xmlns.com/foaf/0.1/',NULL,NULL,'A foaf:LabelProperty is any RDF property with texual values that serve as labels.');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/Person','http://xmlns.com/foaf/0.1/',NULL,NULL,'A person.');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/Agent','http://xmlns.com/foaf/0.1/',NULL,NULL,'An agent (eg. person, group, software or physical artifact).');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/Organization','http://xmlns.com/foaf/0.1/',NULL,NULL,'An organization.');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/Project','http://xmlns.com/foaf/0.1/',NULL,NULL,'A project (a collective endeavour of some kind).');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/Document','http://xmlns.com/foaf/0.1/',NULL,NULL,'A document.');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/Group','http://xmlns.com/foaf/0.1/',NULL,NULL,'A class of Agents.');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/Image','http://xmlns.com/foaf/0.1/',NULL,NULL,'An image.');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/PersonalProfileDocument','http://xmlns.com/foaf/0.1/',NULL,NULL,'A personal profile RDF document.');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/OnlineAccount','http://xmlns.com/foaf/0.1/',NULL,NULL,'An online account.');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/OnlineGamingAccount','http://xmlns.com/foaf/0.1/',NULL,NULL,'An online gaming account.');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/OnlineEcommerceAccount','http://xmlns.com/foaf/0.1/',NULL,NULL,'An online e-commerce account.');
REPLACE INTO classes VALUES('http://xmlns.com/foaf/0.1/OnlineChatAccount','http://xmlns.com/foaf/0.1/',NULL,NULL,'An online chat account.');

REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Agent','en','Agent');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Document','en','Document');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Group','en','Group');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Image','en','Image');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/LabelProperty','en','Label Property');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/OnlineAccount','en','Online Account');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/OnlineChatAccount','en','Online Chat Account');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/OnlineEcommerceAccount','en','Online E-commerce Account');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/OnlineGamingAccount','en','Online Gaming Account');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Organization','en','Organization');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Person','en','Person');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/PersonalProfileDocument','en','PersonalProfileDocument');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Project','en','Project');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/account','en','account');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/accountName','en','account name');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/accountServiceHomepage','en','account service homepage');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/age','en','age');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/aimChatID','en','AIM chat ID');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/based_near','en','based near');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/birthday','en','birthday');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/currentProject','en','current project');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/depiction','en','depiction');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/depicts','en','depicts');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/dnaChecksum','en','DNA checksum');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/familyName','en','familyName');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/family_name','en','family_name');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/firstName','en','firstName');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/focus','en','focus');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/fundedBy','en','funded by');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/geekcode','en','geekcode');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/gender','en','gender');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/givenName','en','Given name');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/givenname','en','Given name');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/holdsAccount','en','account');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/homepage','en','homepage');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/icqChatID','en','ICQ chat ID');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/img','en','image');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/interest','en','interest');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/isPrimaryTopicOf','en','is primary topic of');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/jabberID','en','jabber ID');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/knows','en','knows');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/lastName','en','lastName');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/logo','en','logo');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/made','en','made');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/maker','en','maker');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/mbox','en','personal mailbox');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/mbox_sha1sum','en','sha1sum of a personal mailbox URI name');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/member','en','member');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/membershipClass','en','membershipClass');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/msnChatID','en','MSN chat ID');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/myersBriggs','en','myersBriggs');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/name','en','name');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/nick','en','nickname');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/openid','en','openid');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/page','en','page');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/pastProject','en','past project');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/phone','en','phone');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/plan','en','plan');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/primaryTopic','en','primary topic');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/publications','en','publications');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/schoolHomepage','en','schoolHomepage');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/sha1','en','sha1sum (hex)');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/skypeID','en','Skype ID');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/status','en','status');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/surname','en','Surname');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/theme','en','theme');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/thumbnail','en','thumbnail');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/tipjar','en','tipjar');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/title','en','title');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/topic','en','topic');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/topic_interest','en','topic_interest');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/weblog','en','weblog');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/workInfoHomepage','en','work info homepage');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/workplaceHomepage','en','workplace homepage');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/yahooChatID','en','Yahoo chat ID');

REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Agent','de','Agent');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Document','de','Dokument');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Group','de','Gruppe');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Image','de','Bild');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/LabelProperty','de','Label Property');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Organization','de','Organisation');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Person','de','Person');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/Project','de','Projekt');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/age','de','Alter');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/birthday','de','Geburtstag');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/familyName','de','Familienname');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/family_name','de','Familienname');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/firstName','de','Vorname');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/fundedBy','de','finanziert von');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/gender','de','Gender');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/givenName','de','Vorname');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/givenname','de','Vorname');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/homepage','de','Homepage');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/img','de','Bild');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/interest','de','Interessen');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/knows','de','kennt');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/lastName','de','Nachname');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/logo','de','Logo');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/name','de','Name');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/nick','de','Spitzname');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/page','de','Seite');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/phone','de','Telefon');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/publications','de','Publikationen');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/status','de','Status');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/surname','de','Nachname');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/title','de','Title');
REPLACE INTO labels VALUES('http://xmlns.com/foaf/0.1/topic','de','Thema');
