ALTER TABLE images ADD COLUMN brightness INTEGER NOT NULL DEFAULT 0;
ALTER TABLE images ADD COLUMN contrast INTEGER NOT NULL DEFAULT 0;
ALTER TABLE images ADD COLUMN hue INTEGER NOT NULL DEFAULT 0;
ALTER TABLE images ADD COLUMN saturation INTEGER NOT NULL DEFAULT 0;
