--
-- This file is auto-generated by executing all current
-- migrations. Instead of editing this file, please create
-- migrations to incrementally modify the database, and
-- then regenerate this schema file.
--
-- To create a new empty migration, run:
--   node scripts/db migration -- ontology [name] [sql|js]
--
-- To re-generate this file, run:
--   node scripts/db migrate
--

-- Save the current migration number
PRAGMA user_version=1705231144;

-- Load sqlite3 .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE vocabularies (
  vocabulary_uri  TEXT     NOT NULL PRIMARY KEY,
  created         NUMERIC  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  prefix          TEXT,
  description     TEXT,

  CHECK (vocabulary_uri != ''),
  CHECK (prefix != ''),
  UNIQUE (prefix)
);
CREATE TABLE properties (
  property_uri    TEXT NOT NULL PRIMARY KEY,
  vocabulary_uri  TEXT NOT NULL REFERENCES vocabularies ON DELETE CASCADE,
  domain          TEXT REFERENCES classes (class_uri),
  range           TEXT REFERENCES classes (class_uri),
  parent          TEXT REFERENCES properties (property_uri),
  definition      TEXT,
  comment         TEXT,

  CHECK (property_uri != ''),
  CHECK (parent != ''),
  CHECK (domain != ''),
  CHECK (range != '')
);
CREATE TABLE classes (
  class_uri       TEXT NOT NULL PRIMARY KEY,
  vocabulary_uri  TEXT NOT NULL REFERENCES vocabularies ON DELETE CASCADE,
  definition      TEXT,
  comment         TEXT,
  parent          TEXT REFERENCES classes (class_uri),

  CHECK (class_uri != ''),
  CHECK (parent != '')
);
CREATE TABLE labels (
  uri       TEXT NOT NULL,
  language  TEXT NOT NULL COLLATE NOCASE,
  label     TEXT NOT NULL,

  PRIMARY KEY (uri, language),
  CHECK (uri != ''),
  CHECK (language != '' AND language = trim(lower(language))),
  CHECK (label != '')
) WITHOUT ROWID;
CREATE TABLE templates (
  template_uri   TEXT     NOT NULL PRIMARY KEY,
  template_type  TEXT     NOT NULL DEFAULT 'item',
  protected      BOOLEAN  NOT NULL DEFAULT FALSE,
  created        NUMERIC  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified       NUMERIC  NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CHECK (template_uri != ''),
  CHECK (template_type IN ('item', 'photo', 'selection'))
);
CREATE TABLE template_classes (
  template_uri  TEXT     NOT NULL REFERENCES templates ON DELETE CASCADE,
  class_uri     TEXT     NOT NULL REFERENCES classes,
  position      INTEGER
);
CREATE TABLE template_fields (
  field_id      INTEGER  PRIMARY KEY,
  template_uri  TEXT     NOT NULL REFERENCES templates ON DELETE CASCADE,
  property_uri  TEXT     NOT NULL REFERENCES properties,
  position      INTEGER
);
COMMIT;
PRAGMA foreign_keys=ON;