'use strict'

module.exports = {
  ...require('./activity'),
  ...require('./context'),
  ...require('./edit'),
  ...require('./esper'),
  ...require('./flash'),
  ...require('./history'),
  ...require('./import'),
  ...require('./intl'),
  ...require('./items'),
  ...require('./keymap'),
  ...require('./lists'),
  ...require('./metadata'),
  ...require('./nav'),
  ...require('./notes'),
  ...require('./notepad'),
  ...require('./ontology'),
  ...require('./panel'),
  ...require('./photos'),
  ...require('./prefs'),
  ...require('./project'),
  ...require('./qr'),
  ...require('./recent'),
  ...require('./selections'),
  ...require('./settings'),
  ...require('./sidebar'),
  ...require('./tags'),
  ...require('./ui'),
  ...require('./wizard')
}
