linux:
  - &file
    label: '&File'
    id: 'file'
    submenu:
      - &new
        label: 'New'
        submenu:
          - label: 'Project'
            command: 'app:create-project'
            accelerator: 'CmdOrCtrl+Shift+P'
          - label: 'Item'
            command: 'app:create-item'
          - label: 'List'
            command: 'app:create-list'
          - label: 'Tag'
            command: 'app:create-tag'
      - type: 'separator'
      - &open
        label: 'Open'
        accelerator: 'CmdOrCtrl+O'
        command: 'app:open-dialog'
      - &recent
        label: 'Recent Projects'
        id: 'recent'
        enabled: false
        submenu:
          - type: 'separator'
          - label: 'Clear List'
            command: 'app:clear-recent-projects'
      - type: 'separator'
      - &import
        label: 'Import Photos…'
        command: 'app:import-photos'
        accelerator: 'CmdOrCtrl+Shift+I'        
      - type: 'separator'
      - label: 'Close'
        accelerator: 'CmdOrCtrl+W'
        role: 'close'
      - type: 'separator'
      - label: 'Quit'
        accelerator: 'CmdOrCtrl+Q'
        role: 'quit'
  - &edit
    label: '&Edit'
    submenu:
      - &undo
        id: 'undo'
        label: '&Undo'
        accelerator: 'CmdOrCtrl+Z'
        command: 'app:undo'
        enabled: false
      - &redo
        id: 'redo'
        label: '&Redo'
        accelerator: 'Shift+CmdOrCtrl+Z'
        command: 'app:redo'
        enabled: false
      - type: 'separator'
      - &cut
        label: 'Cu&t'
        accelerator: 'CmdOrCtrl+X'
        role: 'cut'
      - &copy
        label: '&Copy'
        accelerator: 'CmdOrCtrl+C'
        role: 'copy'
      - &paste
        label: '&Paste'
        accelerator: 'CmdOrCtrl+V'
        role: 'paste'
      - type: 'separator'
      - &select-all
        label: 'Select &All'
        accelerator: 'CmdOrCtrl+A'
        role: 'selectall'
      - type: 'separator'
      - &preferences
        label: 'Prefere&nces …'
        accelerator: 'Shift+Control+S'
        command: 'app:open-preferences'
  - &view
    label: '&View'
    submenu:
      - label: 'Toggle &Full Screen'
        role: 'togglefullscreen'
      - label: 'Toggle Hide &Menu Bar'
        command: 'app:toggle-menu-bar'
      - label: 'Hide &Sidebar'
        command: 'app:toggle-sidebar'
        enabled: false
  - &win
    label: 'Window'
    submenu:
      - label: 'Minimize'
        accelerator: 'CmdOrCtrl+M'
        role: 'minimize'
  - &dev
    label: 'Developer'
    id: 'dev'
    submenu:
      - label: '&Reload'
        accelerator: 'CmdOrCtrl+R'
        command: 'win:reload'
      - label: 'Reload &Styles'
        accelerator: 'CmdOrCtrl+S'
        command: 'win:refresh'
      - label: 'Toggle &Developer Tools'
        accelerator: 'CmdOrCtrl+Shift+I'
        role: 'toggledevtools'
      - label: 'Toggle Performance Tools'
        command: 'win:toggle-perf-tools'
      - type: 'separator'
      - label: 'Reset Ontology Database'
        command: 'app:reset-ontology-db'
      - label: 'Close Project'
        command: 'app:close-project'
      - type: 'separator'
      - label: 'Theme'
        id: 'theme'
        submenu:
          - label: 'Light'
            id: 'light'
            type: 'checkbox'
          - label: 'Dark'
            id: 'dark'
            type: 'checkbox'

  - &help
    label: 'Help'
    submenu:
      - label: 'User Guide'
        command: 'app:open-docs'
      - label: 'Support Forums'
        command: 'app:open-forums'
      - type: 'separator'
      - label: 'Software &License'
        command: 'app:open-license'
      - label: 'Show Log Files'
        command: 'app:open-logs'
      - type: 'separator'
      - label: 'About %name'
        command: 'app:about'

darwin:
  - label: '%name'
    submenu:
      - label: 'About %name'
        role: 'about'
      - type: 'separator'
      - label: 'Preferences …'
        accelerator: 'Command+,'
        command: 'app:open-preferences'
      - type: 'separator'
      - label: 'Hide %name'
        accelerator: 'Command+H'
        role: 'hide'
      - label: 'Hide Others'
        accelerator: 'Command+Shift+H'
        role: 'hideothers'
      - label: 'Show All'
        role: 'unhide'
      - type: 'separator'
      - label: 'Quit'
        accelerator: 'Command+Q'
        role: 'quit'

  - label: 'File'
    submenu:
      - *new
      - type: 'separator'
      - *open
      - *recent
      - type: 'separator'
      - *import
      - type: 'separator'
      - label: 'Close'
        accelerator: 'Command+W'
        role: 'close'
  - label: 'Edit'
    submenu:
      - *undo
      - *redo
      - type: 'separator'
      - *cut
      - *copy
      - *paste
      - *select-all
  - *view
  - label: 'Window'
    role: 'window'
    submenu:
      - label: 'Minimize'
        accelerator: 'CmdOrCtrl+M'
        role: 'minimize'
      - label: 'Close'
        accelerator: 'CmdOrCtrl+W'
        role: 'close'
      - type: 'separator'
      - label: 'Bring All to Front'
        role: 'front'
  - *dev
  - label: 'Help'
    role: 'help'
    submenu:
      - label: 'User Guide'
        command: 'app:open-docs'
      - label: 'Support Forums'
        command: 'app:open-forums'
      - type: 'separator'
      - label: 'Software License'
        command: 'app:open-license'      
      - label: 'Show Log Files'
        command: 'app:open-logs'

win32:
  - *file
  - label: '&Edit'
    submenu:
      - *undo
      - id: 'redo'
        label: '&Redo'
        accelerator: 'Control+Y'
        command: 'app:redo'
        enabled: false
      - type: 'separator'
      - *cut
      - *copy
      - *paste
      - *select-all
      - *preferences
  - *view
  - *win
  - *dev
  - *help
