name: wdio
on:
  push:
    branches: [feature/wdio]

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.image }} ${{ matrix.arch }} ${{ matrix.tag }}
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ubuntu-22.04
            arch: x64
          - image: ubuntu-24.04
            arch: x64
            tag: 'shared'
          - image: windows-2022
            arch: x64
          - image: windows-11-arm
            arch: arm64
          - image: macos-15-intel
            arch: x64
          - image: macos-26
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          architecture: ${{ matrix.nodejs_arch || matrix.arch }}
          cache: npm
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install requirements for node-gyp
        run: pip install setuptools

      - name: Install NPM modules
        run: npm clean-install --no-progress --ignore-scripts
      - name: Install Electron
        run: npm rebuild electron

      - name: Install system libvips
        if: runner.os == 'Linux' && matrix.tag == 'shared'
        run: |
          # Install libvips dependencies
          sudo apt-get update
          sudo apt-get install meson pkg-config \
            libarchive-dev libcgif-dev libexif-dev libheif-dev libheif-plugin-aomenc \
            libimagequant-dev libjpeg-dev libjxl-dev liblcms2-dev libopenjp2-7-dev libpango1.0-dev \
            libpng-dev libpoppler-glib-dev librsvg2-dev libtiff5-dev libwebp-dev
          # Fetch required libvips
          mkdir vendor/vips
          export VV=$(jq .config.libvips node_modules/sharp/package.json | tr -d "><='\"")
          curl -sL --retry 3 https://github.com/libvips/libvips/releases/download/v${VV}/vips-${VV}.tar.xz \
            | tar xJC vendor/vips --strip-components=1
          # Build and install libvips
          cd vendor/vips
          meson setup build
          meson compile -C build
          sudo meson install -C build
          # Set env variable
          echo "SHARP_FORCE_GLOBAL_LIBVIPS=true" >> $GITHUB_ENV

      - name: Rebuild native modules
        run: node scripts/rebuild.js --force --verbose --arch ${{ matrix.arch }}

      - name: Create production build
        run: npm run build
        env:
          npm_config_arch: ${{ matrix.arch }}

      - name: Install wdio dependencies
        run: npm --prefix test/wdio clean-install --no-progress

      - name: Run smoke tests
        run: npm run test:wdio
