name: test-package
on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.image }} ${{ matrix.arch }}
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: windows-2022
            arch: x64
          - image: windows-2022
            arch: ia32
            nodejs_arch: x64
          - image: windows-11-arm
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          architecture: ${{ matrix.nodejs_arch || matrix.arch }}
          cache: npm
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install requirements for node-gyp
        run: pip install setuptools

      - name: Install NPM modules
        run: npm clean-install --no-progress

      - name: Rebuild native modules
        run: node scripts/rebuild.js --force --verbose --arch ${{ matrix.arch }}

      - name: Create production build
        run: npm run build
        env:
          npm_config_arch: ${{ matrix.arch }}

      - name: Create package
        run: npm run pack
        env:
          npm_config_arch: ${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}
          path: |
            dist/*.exe
            dist/*.nupkg
